package compiler

// render.go turns a RuntimeModel into the on-disk text artifacts.
// It is the only place that produces output strings; all logic lives in
// build.go. Keeping them separate makes determinism tests easy: compile the
// same model twice and compare bytes.

import (
	"fmt"
	"strings"
)

const generatedHeader = "# Generated by OwnBase — do not hand-edit.\n# Changes here will be overwritten and flagged as a tamper signal.\n"

// render produces the RuntimeOutput (map of filename → content) from a
// RuntimeModel. Deterministic: given the same model it always produces
// byte-identical output.
func render(model RuntimeModel) RuntimeOutput {
	out := RuntimeOutput{
		QuadletUnits: make(map[string]string),
	}

	for _, c := range model.Containers {
		filename := fmt.Sprintf("%s.container", c.Name)
		out.QuadletUnits[filename] = renderContainer(c)
	}

	for _, net := range model.Networks {
		filename := fmt.Sprintf("%s.network", net.Name)
		out.QuadletUnits[filename] = renderNetwork(net)
	}

	for _, vol := range model.Volumes {
		filename := fmt.Sprintf("%s.volume", vol.Name)
		out.QuadletUnits[filename] = renderVolume(vol)
	}

	out.Caddyfile = renderCaddyfile(model.Routes, model.ACMEEmail)
	out.ComposeFile = renderCompose(model)

	return out
}

func renderContainer(c ContainerModel) string {
	var b strings.Builder
	b.WriteString(generatedHeader)

	b.WriteString("\n[Unit]\n")
	fmt.Fprintf(&b, "Description=OwnBase container: %s\n", c.Name)
	b.WriteString("After=network-online.target\n")

	b.WriteString("\n[Container]\n")
	if c.Digest != "" {
		// Digest-pinned pull (core packages): pull Image@Digest for reproducibility.
		fmt.Fprintf(&b, "Image=%s@%s\n", c.Image, c.Digest)
	} else {
		fmt.Fprintf(&b, "Image=%s\n", c.Image)
	}
	fmt.Fprintf(&b, "ContainerName=%s\n", c.Name)

	for _, net := range c.Networks {
		fmt.Fprintf(&b, "Network=%s.network\n", net)
	}

	// Named volume mounts.
	for _, vm := range c.VolumeMounts {
		fmt.Fprintf(&b, "Volume=%s:%s\n", vm.VolumeName, vm.MountPath)
	}

	// Dev-bridge loopback publish — used only by `ownbasectl dev`'s SSH
	// tunnel; Caddy itself addresses containers by name over the internal
	// Podman network and never touches this. Host and container ports are
	// deliberately different numbers (see ContainerModel.DevBridgePort) so
	// this can never collide with Caddy's own machine-wide bind or with
	// another service's loopback publish.
	if c.DevBridgePort > 0 {
		fmt.Fprintf(&b, "PublishPort=127.0.0.1:%d:%d\n", c.DevBridgePort, c.PublicPort)
	}

	// Static environment variables (plaintext; use ownbasectl secrets for sensitive values).
	// Values containing spaces must be double-quoted in the systemd/Quadlet
	// Environment= directive, otherwise systemd parses each word as a separate
	// assignment (e.g. "KEY=val with spaces" → KEY=val, with=, spaces=).
	for _, kv := range c.Env {
		if idx := strings.Index(kv, "="); idx >= 0 && strings.Contains(kv[idx+1:], " ") {
			fmt.Fprintf(&b, "Environment=\"%s\"\n", kv)
		} else {
			fmt.Fprintf(&b, "Environment=%s\n", kv)
		}
	}

	// Health probe — the agent polls this path after start before declaring success.
	if c.HealthProbe != nil && c.HealthProbe.HTTPPath != "" {
		fmt.Fprintf(&b, "# HealthProbeHTTP=%s\n", c.HealthProbe.HTTPPath)
	}

	// Dependency provenance — the agent starts providers before consumers
	// and gates consumer start on each provider's health probe.
	// Format: # Requires=dep1,dep2 (sorted, comma-separated service names).
	if len(c.Requires) > 0 {
		fmt.Fprintf(&b, "# Requires=%s\n", strings.Join(c.Requires, ","))
	}

	// Build provenance — the agent reads these to know where to build from.
	// Omitted for image-bundled core packages (no build step).
	if !c.IsImageBundled {
		if c.BuildSource != "" {
			fmt.Fprintf(&b, "# BuildSource=%s\n", c.BuildSource)
		}
		if c.BuildRef != "" {
			fmt.Fprintf(&b, "# BuildRef=%s\n", c.BuildRef)
		}
		if c.BuildDockerfile != "" {
			fmt.Fprintf(&b, "# BuildDockerfile=%s\n", c.BuildDockerfile)
		}
		if c.BuildContext != "" {
			fmt.Fprintf(&b, "# BuildContext=%s\n", c.BuildContext)
		}
	}

	// Security hardening — apply to every container unit.
	// NoNewPrivileges prevents setuid/setgid privilege escalation inside the container.
	// DropCapability=ALL removes all Linux capabilities; services that genuinely
	// need one (e.g. NET_BIND_SERVICE) must declare it via add_capabilities:.
	b.WriteString("NoNewPrivileges=true\n")
	b.WriteString("DropCapability=ALL\n")
	if c.User != "" {
		fmt.Fprintf(&b, "User=%s\n", c.User)
	}
	for _, cap := range c.AddCapabilities {
		fmt.Fprintf(&b, "AddCapability=%s\n", cap)
	}
	for _, opt := range c.SecurityOpts {
		fmt.Fprintf(&b, "PodmanArgs=--security-opt %s\n", opt)
	}

	b.WriteString("\n[Service]\n")
	b.WriteString("Restart=always\n")
	// Core packages (image-bundled, large pulls) get a longer start timeout.
	// User services build from localhost and start quickly.
	if c.IsImageBundled {
		b.WriteString("TimeoutStartSec=120\n")
	} else {
		b.WriteString("TimeoutStartSec=30\n")
	}

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")

	return b.String()
}

func renderNetwork(net NetworkModel) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n[Network]\n")
	fmt.Fprintf(&b, "# OwnBase capability network: %s\n", net.Name)
	b.WriteString("Driver=bridge\n")
	b.WriteString("Internal=true\n")
	return b.String()
}

func renderVolume(vol VolumeModel) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n[Volume]\n")
	fmt.Fprintf(&b, "# OwnBase data volume: %s\n", vol.Name)
	return b.String()
}

func renderCaddyfile(routes []RouteModel, acmeEmail string) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n")

	if acmeEmail != "" {
		fmt.Fprintf(&b, "{\n\temail %s\n}\n\n", acmeEmail)
	}

	if len(routes) == 0 {
		b.WriteString("# No public routes.\n")
		return b.String()
	}

	for _, r := range routes {
		fmt.Fprintf(&b, "%s {\n", r.Host)
		fmt.Fprintf(&b, "\treverse_proxy %s\n", r.Upstream)
		b.WriteString("}\n\n")
	}
	return b.String()
}

// renderCompose produces a docker-compose-shaped YAML for inspection and
// portability (Architecture Principle 8). Not the runtime format — Quadlet is.
func renderCompose(model RuntimeModel) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n")
	b.WriteString("# Compose export: for inspection and portability only.\n")
	b.WriteString("# The authoritative runtime format is the Quadlet units above.\n\n")
	b.WriteString("services:\n")
	for _, c := range model.Containers {
		fmt.Fprintf(&b, "  %s:\n", sanitizeComposeKey(c.Name))
		fmt.Fprintf(&b, "    image: %q\n", c.Image)
		if len(c.Networks) > 0 {
			b.WriteString("    networks:\n")
			for _, net := range c.Networks {
				fmt.Fprintf(&b, "      - %s\n", sanitizeComposeKey(net))
			}
		}
		b.WriteString("    restart: always\n")
	}

	if len(model.Networks) > 0 {
		b.WriteString("\nnetworks:\n")
		for _, net := range model.Networks {
			fmt.Fprintf(&b, "  %s:\n", sanitizeComposeKey(net.Name))
			b.WriteString("    driver: bridge\n")
			b.WriteString("    internal: true\n")
		}
	}

	if len(model.Volumes) > 0 {
		b.WriteString("\nvolumes:\n")
		for _, vol := range model.Volumes {
			fmt.Fprintf(&b, "  %s:\n", sanitizeComposeKey(vol.Name))
		}
	}

	return b.String()
}

func sanitizeComposeKey(s string) string {
	return strings.ReplaceAll(s, ".", "_")
}
