#!/usr/bin/env bash
# Publish Casks/ownbase.rb to ownbase-ai/homebrew-tap for the desktop app.
#
# Expects the two macOS DMGs already on the GitHub Release for TAG
# (OwnBase-<tag>-aarch64-apple-darwin.dmg and …-x86_64-apple-darwin.dmg).
#
# Env:
#   TAG                          — release tag, e.g. v0.4.1
#   HOMEBREW_TAP_GITHUB_TOKEN    — push access to ownbase-ai/homebrew-tap
#   GH_TOKEN                     — read access to ownbase-ai/ownbase releases
#                                  (defaults to HOMEBREW_TAP_GITHUB_TOKEN)
set -euo pipefail

TAG="${TAG:?TAG is required (e.g. v0.4.1)}"
TOKEN="${HOMEBREW_TAP_GITHUB_TOKEN:?HOMEBREW_TAP_GITHUB_TOKEN is required}"
GH_TOKEN="${GH_TOKEN:-$TOKEN}"
export GH_TOKEN

if [[ ! "$TAG" =~ ^v[0-9] ]]; then
  echo "TAG must look like vX.Y.Z, got: $TAG" >&2
  exit 1
fi
version="${TAG#v}"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

echo "==> Fetching macOS DMGs from release $TAG"
gh release download "$TAG" \
  --repo ownbase-ai/ownbase \
  --dir "$work" \
  --pattern "OwnBase-${TAG}-aarch64-apple-darwin.dmg" \
  --pattern "OwnBase-${TAG}-x86_64-apple-darwin.dmg"

arm_dmg="$work/OwnBase-${TAG}-aarch64-apple-darwin.dmg"
intel_dmg="$work/OwnBase-${TAG}-x86_64-apple-darwin.dmg"
for f in "$arm_dmg" "$intel_dmg"; do
  if [[ ! -f "$f" ]]; then
    echo "missing release asset: $(basename "$f")" >&2
    ls -la "$work" >&2 || true
    exit 1
  fi
done

arm_sha=$(shasum -a 256 "$arm_dmg" | awk '{print $1}')
intel_sha=$(shasum -a 256 "$intel_dmg" | awk '{print $1}')
echo "    arm64  $arm_sha"
echo "    amd64  $intel_sha"

cask_body=$(cat <<RUBY
# This file is generated by OwnBase release CI. DO NOT EDIT.
cask "ownbase" do
  version "${version}"

  on_macos do
    on_intel do
      sha256 "${intel_sha}"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/OwnBase-v#{version}-x86_64-apple-darwin.dmg"
    end
    on_arm do
      sha256 "${arm_sha}"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/OwnBase-v#{version}-aarch64-apple-darwin.dmg"
    end
  end

  name "OwnBase"
  desc "Set up a Base, watch its health, and replay every session opened on it"
  homepage "https://ownbase.ai"

  depends_on macos: ">= :big_sur"

  app "OwnBase.app"

  # The binaries are not Apple-notarized; strip the quarantine attribute on
  # install so macOS Gatekeeper does not block the first launch.
  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/OwnBase.app"]
    end
  end

  zap trash: [
    "~/Library/Application Support/ai.ownbase.desktop",
    "~/Library/Caches/ai.ownbase.desktop",
    "~/Library/Preferences/ai.ownbase.desktop.plist",
    "~/Library/WebKit/ai.ownbase.desktop",
  ]
end
RUBY
)

echo "==> Updating ownbase-ai/homebrew-tap"
tap="$work/homebrew-tap"
git clone --depth=1 \
  "https://x-access-token:${TOKEN}@github.com/ownbase-ai/homebrew-tap.git" \
  "$tap"
mkdir -p "$tap/Casks"
printf '%s\n' "$cask_body" > "$tap/Casks/ownbase.rb"

git -C "$tap" config user.name "github-actions[bot]"
git -C "$tap" config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git -C "$tap" add Casks/ownbase.rb

if git -C "$tap" diff --cached --quiet; then
  echo "    Casks/ownbase.rb already at $version — nothing to push"
  exit 0
fi

git -C "$tap" commit -m "ownbase ${version}"
git -C "$tap" push origin HEAD:main
echo "==> Published ownbase ${version} to homebrew-tap"
