#!/usr/bin/env bash
# Publish Casks/ownbasectl.rb to ownbase-ai/homebrew-tap from a GitHub Release.
#
# Env:
#   TAG                          — release tag, e.g. v0.5.0
#   HOMEBREW_TAP_GITHUB_TOKEN    — push access to ownbase-ai/homebrew-tap
#   GH_TOKEN                     — read ownbase-ai/ownbase releases
set -euo pipefail

TAG="${TAG:?TAG is required (e.g. v0.5.0)}"
TOKEN="${HOMEBREW_TAP_GITHUB_TOKEN:?HOMEBREW_TAP_GITHUB_TOKEN is required}"
GH_TOKEN="${GH_TOKEN:-$TOKEN}"
export GH_TOKEN

if [[ ! "$TAG" =~ ^v[0-9] ]]; then
  echo "TAG must look like vX.Y.Z, got: $TAG" >&2
  exit 1
fi
version="${TAG#v}"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

echo "==> Fetching ownbasectl archives from release $TAG"
gh release download "$TAG" \
  --repo ownbase-ai/ownbase \
  --dir "$work" \
  --pattern "ownbasectl_${version}_darwin_amd64.tar.gz" \
  --pattern "ownbasectl_${version}_darwin_arm64.tar.gz" \
  --pattern "ownbasectl_${version}_linux_amd64.tar.gz" \
  --pattern "ownbasectl_${version}_linux_arm64.tar.gz"

sha() { shasum -a 256 "$1" | awk '{print $1}'; }

darwin_amd=$(sha "$work/ownbasectl_${version}_darwin_amd64.tar.gz")
darwin_arm=$(sha "$work/ownbasectl_${version}_darwin_arm64.tar.gz")
linux_amd=$(sha "$work/ownbasectl_${version}_linux_amd64.tar.gz")
linux_arm=$(sha "$work/ownbasectl_${version}_linux_arm64.tar.gz")

cat > "$work/ownbasectl.rb" <<RUBY
# This file is generated by OwnBase release CI. DO NOT EDIT.
cask "ownbasectl" do
  version "${version}"

  on_macos do
    on_intel do
      sha256 "${darwin_amd}"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "${darwin_arm}"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "${linux_amd}"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "${linux_arm}"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ownbasectl"
  desc "Set up, operate, and own your Base — the OwnBase CLI"
  homepage "https://ownbase.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ownbasectl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ownbasectl"]
    end
  end
end
RUBY

echo "==> Pushing Casks/ownbasectl.rb to ownbase-ai/homebrew-tap"
tap=$(mktemp -d)
trap 'rm -rf "$work" "$tap"' EXIT
git clone --depth 1 "https://x-access-token:${TOKEN}@github.com/ownbase-ai/homebrew-tap.git" "$tap"
mkdir -p "$tap/Casks"
cp "$work/ownbasectl.rb" "$tap/Casks/ownbasectl.rb"
git -C "$tap" config user.name "ownbase-release[bot]"
git -C "$tap" config user.email "release@ownbase.ai"
git -C "$tap" add Casks/ownbasectl.rb
if git -C "$tap" diff --cached --quiet; then
  echo "    already up to date"
  exit 0
fi
git -C "$tap" commit -m "ownbasectl ${version}"
git -C "$tap" push origin HEAD:main
echo "==> ownbasectl cask ${version} published"
