package main

// devtls.go implements local HTTPS simulation for Multipass Bases: mkcert
// wildcard certificates trusted by the host, and the /etc/hosts management
// that maps hostnames like forgejo.mybase.test to the VM's IP.
//
// Three entry points into this file:
//   - `ownbasectl create` (create.go) calls the mkcert helpers to generate
//     and transfer the initial wildcard certificate, and writeHostsBlock to
//     seed the initial /etc/hosts entries.
//   - `ownbasectl vm start/restart` (vm.go) calls writeHostsBlock after
//     re-detecting the VM's IP.
//   - `ownbasectl dev-tls sync/trust` (this file) are the user-facing
//     commands for refreshing hostnames after adding services, and for
//     re-trusting the mkcert CA (e.g. after `mkcert -uninstall`, or on a new
//     machine).
//
// mkcert (https://github.com/FiloSottile/mkcert) is a local-only CA: its
// private key never leaves the host running `ownbasectl`, so trusting it
// only affects certificates generated by this same mkcert installation.

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/ownbase/ownbase/internal/schema"
	"github.com/ownbase/ownbase/internal/serverconfig"
	"github.com/ownbase/ownbase/internal/tunnel"
)

// mkcertInstallHint is shown whenever a dev-TLS operation needs mkcert but
// it is not on PATH. Callers that can gracefully fall back to plain HTTP
// (create.go) print this as a warning; commands with no fallback (dev-tls
// sync/trust) return it as an error.
const mkcertInstallHint = "mkcert not found on PATH — install it with 'brew install mkcert nss' " +
	"(see https://github.com/FiloSottile/mkcert), then re-run"

// mkcertAvailable reports whether the mkcert binary is on PATH.
func mkcertAvailable() bool {
	_, err := exec.LookPath("mkcert")
	return err == nil
}

// mkcertEnsureInstalled runs `mkcert -install`, which generates (if needed)
// and trusts mkcert's local CA in the host's system/browser trust stores.
// Idempotent — safe to call on every `create`/`dev-tls trust`.
func mkcertEnsureInstalled() error {
	cmd := exec.Command("mkcert", "-install")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("mkcert -install: %w", err)
	}
	return nil
}

// mkcertGenerateWildcard generates a certificate covering domain and every
// direct subdomain of it (*.domain), writing cert.pem/key.pem into destDir
// (created if needed). Returns the two file paths.
func mkcertGenerateWildcard(domain, destDir string) (certPath, keyPath string, err error) {
	if err := os.MkdirAll(destDir, 0o700); err != nil {
		return "", "", fmt.Errorf("create %s: %w", destDir, err)
	}
	certPath = filepath.Join(destDir, "cert.pem")
	keyPath = filepath.Join(destDir, "key.pem")
	cmd := exec.Command("mkcert",
		"-cert-file", certPath,
		"-key-file", keyPath,
		"*."+domain, domain,
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return "", "", fmt.Errorf("mkcert generate certificate for *.%s: %w", domain, err)
	}
	return certPath, keyPath, nil
}

// ---------------------------------------------------------------------------
// /etc/hosts management
// ---------------------------------------------------------------------------

// hostsBlockMarkers returns the begin/end marker lines that delimit one
// Base's block within /etc/hosts. Keyed by Base name so multiple dev-TLS
// Bases can coexist without clobbering each other's entries.
func hostsBlockMarkers(name string) (begin, end string) {
	return "# BEGIN OWNBASE " + name, "# END OWNBASE " + name
}

// upsertHostsBlock returns a new /etc/hosts content with the named Base's
// marked block replaced (or removed, if hostnames is empty) and re-appended
// at the end. Pure function — no I/O — so it is easy to unit test.
func upsertHostsBlock(current []byte, name, ip string, hostnames []string) []byte {
	begin, end := hostsBlockMarkers(name)
	lines := strings.Split(string(current), "\n")

	out := make([]string, 0, len(lines))
	inBlock := false
	for _, line := range lines {
		switch strings.TrimSpace(line) {
		case begin:
			inBlock = true
			continue
		case end:
			inBlock = false
			continue
		}
		if inBlock {
			continue
		}
		out = append(out, line)
	}

	// Trim trailing blank lines so repeated syncs don't accumulate them.
	for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
		out = out[:len(out)-1]
	}

	if len(hostnames) > 0 {
		sorted := append([]string(nil), hostnames...)
		sort.Strings(sorted)
		out = append(out, "", begin, fmt.Sprintf("%s %s", ip, strings.Join(sorted, " ")), end)
	}

	return []byte(strings.Join(out, "\n") + "\n")
}

// etcHostsPath is a variable (not a constant) so tests can point it at a
// temp file instead of touching the real /etc/hosts.
var etcHostsPath = "/etc/hosts"

// rewriteEtcHosts reads /etc/hosts, applies mutate, and — only if the
// content actually changed — writes it back via `sudo tee`, which prompts
// for the host's password on the controlling terminal. Using `tee` instead
// of a temp file + `cp` means /etc/hosts's existing ownership and
// permissions (root:wheel 0644) are left untouched.
func rewriteEtcHosts(mutate func(current []byte) []byte) error {
	current, err := os.ReadFile(etcHostsPath)
	if err != nil {
		return fmt.Errorf("read /etc/hosts: %w", err)
	}
	updated := mutate(current)
	if bytes.Equal(current, updated) {
		return nil
	}

	fmt.Fprintln(os.Stderr, "ownbasectl: updating /etc/hosts (requires sudo) ...")
	cmd := exec.Command("sudo", "tee", etcHostsPath)
	cmd.Stdin = bytes.NewReader(updated)
	cmd.Stdout = io.Discard
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("write /etc/hosts (needs sudo): %w", err)
	}
	return nil
}

// writeHostsBlock upserts the named Base's /etc/hosts block, mapping ip to
// every hostname in hostnames (order does not matter — upsertHostsBlock
// sorts them). Called by create, vm start/restart, and dev-tls sync.
func writeHostsBlock(name, ip string, hostnames []string) error {
	return rewriteEtcHosts(func(current []byte) []byte {
		return upsertHostsBlock(current, name, ip, hostnames)
	})
}

// removeHostsBlock deletes the named Base's /etc/hosts block, if present.
// Safe to call for a Base that never had one (e.g. --no-dev-tls) — it is
// then a no-op.
func removeHostsBlock(name string) error {
	return rewriteEtcHosts(func(current []byte) []byte {
		return upsertHostsBlock(current, name, "", nil)
	})
}

// existingHostsForBase returns the hostnames currently recorded in the
// named Base's /etc/hosts block (everything after the IP on its single
// entry line), or nil if the Base has no block. Used by `vm start/restart`
// to carry the current hostname set forward onto a freshly re-detected IP
// without needing to SSH into the Base (which may not be reachable yet
// immediately after a Multipass start).
func existingHostsForBase(name string) ([]string, error) {
	data, err := os.ReadFile(etcHostsPath)
	if err != nil {
		return nil, fmt.Errorf("read /etc/hosts: %w", err)
	}
	begin, end := hostsBlockMarkers(name)
	inBlock := false
	var hostnames []string
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		switch trimmed {
		case begin:
			inBlock = true
			continue
		case end:
			inBlock = false
			continue
		}
		if !inBlock || trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		fields := strings.Fields(trimmed)
		if len(fields) > 1 {
			hostnames = append(hostnames, fields[1:]...)
		}
	}
	return hostnames, nil
}

// ---------------------------------------------------------------------------
// Hostname collection from a Base's live ownbase.yaml
// ---------------------------------------------------------------------------

// isCoveredByWildcard reports whether host is domain itself or exactly one
// label under it. Mirrors mkcert's "*.domain" SAN, which — like all wildcard
// TLS certificates — covers "sub.domain" but not "a.b.domain".
func isCoveredByWildcard(host, domain string) bool {
	if host == domain {
		return true
	}
	suffix := "." + domain
	if !strings.HasSuffix(host, suffix) {
		return false
	}
	label := strings.TrimSuffix(host, suffix)
	return label != "" && !strings.Contains(label, ".")
}

// devTLSHostnamesFromYAML parses raw ownbase.yaml content and returns the
// sorted, deduped set of hostnames that should resolve to this Base
// (Forgejo's domain, if set, plus every service domain), and the subset of
// those that fall outside the *.<devDomain> wildcard's coverage (e.g. a
// service given a domain under a different base domain by mistake).
func devTLSHostnamesFromYAML(raw, devDomain string) (all, uncovered []string, err error) {
	cfg, err := schema.ParseConfig(strings.NewReader(raw))
	if err != nil {
		return nil, nil, err
	}

	seen := make(map[string]bool)
	add := func(h string) {
		h = strings.TrimSpace(h)
		if h == "" || seen[h] {
			return
		}
		seen[h] = true
		all = append(all, h)
	}
	add(cfg.Core.Forgejo.Domain)
	for _, svc := range cfg.Services {
		add(svc.Domain)
	}
	sort.Strings(all)

	for _, h := range all {
		if !isCoveredByWildcard(h, devDomain) {
			uncovered = append(uncovered, h)
		}
	}
	return all, uncovered, nil
}

// ---------------------------------------------------------------------------
// ownbasectl dev-tls
// ---------------------------------------------------------------------------

func newDevTLSCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "dev-tls",
		Short: "Manage local HTTPS simulation (mkcert) for a Base",
		Long: `dev-TLS gives a local Multipass Base real HTTPS using mkcert-signed
certificates (trusted by this machine only) and /etc/hosts entries like
forgejo.mybase.test. Enabled by default on 'ownbasectl create' for local
VMs — see --no-dev-tls / --dev-domain.`,
	}
	cmd.AddCommand(newDevTLSSyncCmd(), newDevTLSTrustCmd())
	return cmd
}

func newDevTLSSyncCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "sync <name>",
		Short: "Refresh /etc/hosts for a dev-TLS Base's current service domains",
		Long: `Reads the Base's live ownbase.yaml over SSH and rewrites this machine's
/etc/hosts entry for it so every service domain (and Forgejo's, if set)
resolves to the Base's current IP. Run this after adding a service with a
new domain:. It does not re-detect the VM's IP after a stop/start — use
'ownbasectl vm start' for that.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDevTLSSync(args[0])
		},
	}
}

func newDevTLSTrustCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "trust",
		Short: "Re-run mkcert -install to (re-)trust the local dev-TLS CA",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDevTLSTrust()
		},
	}
}

func runDevTLSTrust() error {
	if !mkcertAvailable() {
		return fmt.Errorf("%s", mkcertInstallHint)
	}
	if err := mkcertEnsureInstalled(); err != nil {
		return err
	}
	fmt.Println("mkcert local CA trusted.")
	return nil
}

func runDevTLSSync(name string) error {
	cfgPath, err := serverconfig.DefaultConfigPath()
	if err != nil {
		return fmt.Errorf("locate config: %w", err)
	}
	cfg, err := serverconfig.Load(cfgPath)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	profile, err := cfg.ProfileFor(name)
	if err != nil {
		return err
	}
	if profile.DevTLSDomain == "" {
		return fmt.Errorf("Base %q is not using dev-TLS (created with --no-dev-tls, --remote, or mkcert was unavailable) — nothing to sync", name)
	}
	if profile.Host == "" {
		return fmt.Errorf("Base %q has no host recorded", name)
	}

	fmt.Fprintf(os.Stderr, "ownbasectl: reading ownbase.yaml from %q ...\n", name)
	raw, err := tunnel.RunCommand(
		profile.Host, profile.EffectiveSSHUser(), profile.EffectiveSSHKey(),
		"cat /opt/ownbase/checkout/ownbase.yaml", profile.EffectiveSSHPort(),
	)
	if err != nil {
		return fmt.Errorf("read ownbase.yaml from %q over SSH: %w", name, err)
	}

	hostnames, uncovered, err := devTLSHostnamesFromYAML(raw, profile.DevTLSDomain)
	if err != nil {
		return fmt.Errorf("parse ownbase.yaml from %q: %w", name, err)
	}
	if len(uncovered) > 0 {
		fmt.Fprintf(os.Stderr,
			"warning: %s not covered by the *.%s dev-TLS certificate (browsers will show an untrusted-certificate warning) — "+
				"re-run 'ownbasectl create %s --dev-domain <domain>' to reissue for a different base domain\n",
			strings.Join(uncovered, ", "), profile.DevTLSDomain, name)
	}

	if err := writeHostsBlock(name, profile.Host, hostnames); err != nil {
		return err
	}

	if len(hostnames) == 0 {
		fmt.Printf("No domains configured for %q yet — removed its /etc/hosts block.\n", name)
		return nil
	}
	fmt.Printf("Synced %d dev-TLS hostname(s) for %q -> %s:\n", len(hostnames), name, profile.Host)
	for _, h := range hostnames {
		fmt.Printf("  https://%s\n", h)
	}
	return nil
}
