package bridge

// certs.go wraps mkcert (https://github.com/FiloSottile/mkcert), a tool
// that creates a local-only certificate authority (CA), installs it into
// the OS/browser trust store once (`mkcert -install`, needs sudo), and then
// issues certificates signed by that CA — trusted only on machines where
// that CA was installed, with zero recurring cost after the one-time
// install. mkcert's private key never leaves the host running ownbasectl,
// so trusting it only affects certificates generated by this same mkcert
// installation.
//
// `mkcert -install` is the *only* sudo prompt anywhere in `ownbasectl tunnel`
// (and in ownbasectl overall) — it is acceptable specifically because
// starting this long-running, explicitly interactive command is itself the
// human's "I am sitting here, ready" signal. `create`/`vm` never
// call anything in this file.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// MkcertInstallHint is shown whenever a tunnel operation needs mkcert
// but it is not on PATH.
const MkcertInstallHint = "mkcert not found on PATH — install it with 'brew install mkcert nss' " +
	"(see https://github.com/FiloSottile/mkcert), then re-run"

// MkcertAvailable reports whether the mkcert binary is on PATH.
func MkcertAvailable() bool {
	_, err := exec.LookPath("mkcert")
	return err == nil
}

// MkcertEnsureInstalled runs `mkcert -install`, which generates (if needed)
// and trusts mkcert's local CA in the host's system/browser trust stores.
// Idempotent — mkcert checks and skips silently once the CA is already
// trusted, so this is safe to call on every `ownbasectl tunnel` invocation; the
// interactive sudo prompt only ever appears the first time it runs on a
// given machine.
func MkcertEnsureInstalled() error {
	cmd := exec.Command("mkcert", "-install")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("mkcert -install: %w", err)
	}
	return nil
}

// GenerateCert generates one certificate covering every hostname in
// hostnames (e.g. the result of AllLocalHostnames), writing cert.pem/key.pem
// into destDir (created if needed). Returns the two file paths.
//
// Because arbitrary production domains are not a single-level suffix of
// anything shared, this cannot be one wildcard certificate the way
// "*.<name>.localhost" could be — mkcert is invoked once with the full,
// explicit list of hostnames as SANs instead (mkcert supports multiple SANs
// per invocation). Because every one of these hostnames ends in
// ".localhost" and always resolves to loopback per RFC 6761 — no DNS, no
// /etc/hosts, works fully offline — none of them ever need to change, so
// the certificate only needs regenerating when the actual set of domain'd
// services changes (add/remove a domain, add/remove a service), never
// because of a VM restart or IP change.
func GenerateCert(hostnames []string, destDir string) (certPath, keyPath string, err error) {
	if len(hostnames) == 0 {
		return "", "", fmt.Errorf("no hostnames to generate a certificate for")
	}
	if err := os.MkdirAll(destDir, 0o700); err != nil {
		return "", "", fmt.Errorf("create %s: %w", destDir, err)
	}
	certPath = filepath.Join(destDir, "cert.pem")
	keyPath = filepath.Join(destDir, "key.pem")

	args := append([]string{"-cert-file", certPath, "-key-file", keyPath}, hostnames...)
	cmd := exec.Command("mkcert", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return "", "", fmt.Errorf("mkcert generate certificate: %w", err)
	}
	return certPath, keyPath, nil
}
