// Package core manages the OwnBase core package: Caddy (reverse proxy). This
// is distinct from user services declared in ownbase.yaml — it is installed
// by the OwnBase installer and updated by ownbasectl upgrade, not by the
// user update loop.
//
// Separation of concerns:
//
//   - User services (declared with repo: in ownbase.yaml) are compiled and
//     reconciled by the agent's normal path.
//   - The core package is always present; the installer brings it up from a
//     pinned image digest; the core package manifest is embedded in the binary.
//
// The core: block in ownbase.yaml configures the core package (domains,
// ports, TLS email) but never controls which version runs — that is
// OwnBase's job.
package core

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ownbase/ownbase/internal/compiler"
	"github.com/ownbase/ownbase/internal/schema"
)

// CoreManifest holds the pinned image reference for the OwnBase core package.
// This digest is updated by the OwnBase team via ownbasectl upgrade.
// The bootstrap exception: this is the only image ever pulled from a
// registry — user services must always be built from local repos.
type CoreManifest struct {
	CaddyImage  string // e.g. "docker.io/library/caddy:2.11.4-alpine"
	CaddyDigest string // e.g. "sha256:..."
}

// Current is the pinned core manifest embedded in this binary.
// Updated with each OwnBase release via ownbasectl upgrade.
//
// Bumped 2026-07-04 to the latest stable release at the time
// (Caddy 2.11.4-alpine), verified with `skopeo inspect`.
var Current = CoreManifest{
	CaddyImage:  "docker.io/library/caddy:2.11.4-alpine",
	CaddyDigest: "sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648",
}

// CaddyContainerName is the well-known name for the core Caddy container.
const CaddyContainerName = "ownbase-core-caddy"

// CaddyDataVolume is the named volume for Caddy's persistent data (certs).
const CaddyDataVolume = "ownbase-core-caddy-data"

// OwnbaseInternalNetwork is the name of the shared internal network used by
// Caddy and other core services that need to communicate without host routing.
const OwnbaseInternalNetwork = "ownbase-internal"

// BuildCoreOutput builds the full RuntimeOutput for the core package.
// This is a separate compile step from the user services; the outputs are
// merged by the agent before applying.
//
// hasPublicDomain reports whether any service in ownbase.yaml has a domain
// configured (schema.OwnbaseConfig.HasPublicDomain). When false — the
// default state of a fresh Base — Caddy publishes no ports at all: there is
// nothing for it to route yet, and `ownbasectl tunnel` reaches services
// directly over SSH, bypassing Caddy entirely.
func BuildCoreOutput(cfg schema.CoreConfig, m CoreManifest, hasPublicDomain bool) compiler.RuntimeOutput {
	caddy := buildCaddyModel(cfg, m, hasPublicDomain)

	out := compiler.RuntimeOutput{
		QuadletUnits: make(map[string]string),
	}

	// Shared internal network unit — required by Caddy so that Quadlet's
	// auto-generated ownbase-internal-network.service dependency is satisfied.
	out.QuadletUnits[OwnbaseInternalNetwork+".network"] = renderCoreNetwork(OwnbaseInternalNetwork)

	// Caddy unit.
	out.QuadletUnits[CaddyContainerName+".container"] = renderCoreContainer(caddy)
	out.QuadletUnits[CaddyDataVolume+".volume"] = renderCoreVolume(CaddyDataVolume)

	return out
}

func buildCaddyModel(cfg schema.CoreConfig, m CoreManifest, hasPublicDomain bool) compiler.ContainerModel {
	env := []string{}
	if cfg.Caddy.Email != "" {
		env = append(env, "ACME_EMAIL="+cfg.Caddy.Email)
	}
	model := compiler.ContainerModel{
		Name:           CaddyContainerName,
		Image:          m.CaddyImage,
		Digest:         m.CaddyDigest,
		IsImageBundled: true,
		Env:            env,
		VolumeMounts: []compiler.VolumeMount{
			{VolumeName: CaddyDataVolume, MountPath: "/data"},
		},
		Networks: []string{"ownbase-internal"},
		// Binding ports <1024 requires CAP_NET_BIND_SERVICE even for root, and
		// every container drops ALL capabilities by default. Caddy runs as the
		// image default user (root in caddy:2-alpine) and needs exactly this one
		// capability back; no User override (forcing a non-root UID would break
		// privileged-port binding and writes to the cert store under /data).
		AddCapabilities: []string{"NET_BIND_SERVICE"},
	}
	// Caddy is the public web entrypoint: it accepts external traffic on 80
	// (ACME HTTP-01 + redirects) and 443 (HTTPS) on all interfaces — but only
	// once there is at least one domain'd service to route to. A domain-less
	// Base publishes nothing here; ownbasectl tunnel reaches services directly.
	if hasPublicDomain {
		model.HostPublishPorts = []int{80, 443}
	}
	return model
}

const coreGeneratedHeader = "# Generated by OwnBase core — do not hand-edit.\n# Core packages are managed by OwnBase, not by ownbase.yaml.\n"

func renderCoreContainer(c compiler.ContainerModel) string {
	var b strings.Builder
	b.WriteString(coreGeneratedHeader)

	b.WriteString("\n[Unit]\n")
	fmt.Fprintf(&b, "Description=OwnBase core: %s\n", c.Name)
	b.WriteString("After=network-online.target\n")

	b.WriteString("\n[Container]\n")
	if c.Digest != "" {
		fmt.Fprintf(&b, "Image=%s@%s\n", c.Image, c.Digest)
	} else {
		fmt.Fprintf(&b, "Image=%s\n", c.Image)
	}
	fmt.Fprintf(&b, "ContainerName=%s\n", c.Name)

	for _, net := range c.Networks {
		fmt.Fprintf(&b, "Network=%s.network\n", net)
	}
	for _, vm := range c.VolumeMounts {
		fmt.Fprintf(&b, "Volume=%s:%s\n", vm.VolumeName, vm.MountPath)
	}
	if c.PublicPort > 0 {
		// Bind to all interfaces when no domain is configured (direct access
		// without Caddy, dev/no-TLS setup). With a domain, Caddy proxies from
		// localhost so 127.0.0.1 is sufficient and avoids external exposure.
		if len(c.PublicDomains) == 0 {
			fmt.Fprintf(&b, "PublishPort=%d:%d\n", c.PublicPort, c.PublicPort)
		} else {
			fmt.Fprintf(&b, "PublishPort=127.0.0.1:%d:%d\n", c.PublicPort, c.PublicPort)
		}
	}
	// Public web entrypoint ports (Caddy 80/443): published on all interfaces
	// so external clients can reach the reverse proxy. UFW already allows 80
	// and 443 inbound; everything else stays loopback-only.
	for _, hp := range c.HostPublishPorts {
		fmt.Fprintf(&b, "PublishPort=%d:%d\n", hp, hp)
	}
	for _, kv := range c.Env {
		fmt.Fprintf(&b, "Environment=%s\n", kv)
	}
	if c.HealthProbe != nil && c.HealthProbe.HTTPPath != "" {
		fmt.Fprintf(&b, "# HealthProbeHTTP=%s\n", c.HealthProbe.HTTPPath)
	}

	// Security hardening.
	b.WriteString("NoNewPrivileges=true\n")
	b.WriteString("DropCapability=ALL\n")
	if c.User != "" {
		fmt.Fprintf(&b, "User=%s\n", c.User)
	}
	for _, cap := range c.AddCapabilities {
		fmt.Fprintf(&b, "AddCapability=%s\n", cap)
	}

	b.WriteString("\n[Service]\n")
	b.WriteString("Restart=always\n")
	b.WriteString("TimeoutStartSec=120\n") // core packages pull large public images

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=default.target\n")

	return b.String()
}

func renderCoreNetwork(name string) string {
	var b strings.Builder
	b.WriteString(coreGeneratedHeader)
	b.WriteString("\n[Network]\n")
	fmt.Fprintf(&b, "# OwnBase core internal network: %s\n", name)
	return b.String()
}

func renderCoreVolume(name string) string {
	var b strings.Builder
	b.WriteString(coreGeneratedHeader)
	b.WriteString("\n[Volume]\n")
	fmt.Fprintf(&b, "# OwnBase core data volume: %s\n", name)
	return b.String()
}

// SortedUnitNames returns the core unit filenames in deterministic order.
func SortedUnitNames(out compiler.RuntimeOutput) []string {
	names := make([]string, 0, len(out.QuadletUnits))
	for k := range out.QuadletUnits {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}
