package install

import (
	"os"
	"strings"

	"github.com/ownbase/ownbase/internal/schema"
)

// FirstRunEnvPath is the one-time credential file written by install.sh and
// consumed by the agent on the first BootstrapCore call. The file is root-only
// (0600) and deleted after successful consumption so credentials are not kept
// on disk longer than needed.
const FirstRunEnvPath = "/opt/ownbase/first-run.env"

// FirstRunEnv holds the values parsed from the one-time first-run.env file
// written by install.sh. All fields are optional — the installer only writes
// values that were explicitly provided or generated.
type FirstRunEnv struct {
	// Password is the Forgejo web-UI login password for the owner account.
	// Always present: generated by install.sh if not supplied by the user.
	Password string

	// SSHKey is the owner's SSH public key to register with Forgejo.
	// Empty when the user did not pass OWNBASE_OWNER_SSH_KEY at install time.
	SSHKey string

	// ForgejoDomain is the public hostname for the Forgejo web UI
	// (e.g. "git.yourdomain.com"). Empty when not provided at install time.
	ForgejoDomain string

	// CaddyEmail is the ACME/Let's Encrypt contact email for automatic TLS.
	// Empty when not provided at install time.
	CaddyEmail string

	// DevTLS mirrors OWNBASE_DEV_TLS from install.sh: true when `ownbasectl
	// create` staged a mkcert-signed certificate for local-VM HTTPS
	// simulation (see internal/core.DevTLSHostDir). Never true for a
	// --remote/production install.
	DevTLS bool
}

// ReadFirstRunEnv parses the first-run configuration from the file at path.
// Returns a zero-value FirstRunEnv when the file does not exist or cannot be
// read. The file is NOT deleted — call DeleteFirstRunEnv after a successful
// bootstrap.
func ReadFirstRunEnv(path string) FirstRunEnv {
	var env FirstRunEnv
	data, err := os.ReadFile(path)
	if err != nil {
		return env
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		switch k {
		case "OWNER_PASSWORD":
			env.Password = v
		case "OWNER_SSH_KEY":
			env.SSHKey = v
		case "FORGEJO_DOMAIN":
			env.ForgejoDomain = v
		case "CADDY_EMAIL":
			env.CaddyEmail = v
		case "DEV_TLS":
			env.DevTLS = v == "1"
		}
	}
	return env
}

// DeleteFirstRunEnv removes the one-time credentials file. Errors are
// silently ignored — the file may already be absent.
func DeleteFirstRunEnv(path string) {
	_ = os.Remove(path)
}

// MergeFirstRunIntoCoreConfig fills in coreCfg's domain/email/dev-TLS from
// firstRun, but only when configExisted is false — i.e. only on a
// genuinely first boot, before ownbase.yaml has ever existed on disk, when
// coreCfg is still just the zero-value default. This is the bridge that
// lets Forgejo/Caddy start with the right settings before the initial
// ownbase.yaml is seeded.
//
// It must be a no-op whenever configExisted is true, most importantly
// after a `restore`: the daemon's `--rebuild` path restores a real
// ownbase.yaml from the backup snapshot *before* the agent's normal
// startup ever calls this, and that file's own domain/email/dev_tls
// (which may be a real ACME domain, not a fresh local dev-TLS one) must
// never be silently overridden by first-run.env, which `restore` also
// writes (carrying whatever dev-TLS default `ownbasectl create`/`restore`
// resolved for this run).
func MergeFirstRunIntoCoreConfig(coreCfg schema.CoreConfig, firstRun FirstRunEnv, configExisted bool) schema.CoreConfig {
	if configExisted {
		return coreCfg
	}
	if firstRun.ForgejoDomain != "" && coreCfg.Forgejo.Domain == "" {
		coreCfg.Forgejo.Domain = firstRun.ForgejoDomain
	}
	if firstRun.CaddyEmail != "" && coreCfg.Caddy.Email == "" {
		coreCfg.Caddy.Email = firstRun.CaddyEmail
	}
	if firstRun.DevTLS {
		coreCfg.Caddy.DevTLS = true
	}
	return coreCfg
}
