// Package reconcile internal tests for topo sort and provenance parsing.
// These tests live in the same package (not _test) to access unexported helpers.
package reconcile

import (
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// parseRequires
// ---------------------------------------------------------------------------

func TestParseRequires_EmptyUnit(t *testing.T) {
	got := parseRequires("# Generated by OwnBase\n[Container]\nImage=localhost/foo:local\n")
	if len(got) != 0 {
		t.Errorf("expected nil, got %v", got)
	}
}

func TestParseRequires_SingleDep(t *testing.T) {
	content := "# Requires=auth\n[Container]\n"
	got := parseRequires(content)
	if len(got) != 1 || got[0] != "auth" {
		t.Errorf("expected [auth], got %v", got)
	}
}

func TestParseRequires_MultipleDeps(t *testing.T) {
	content := "# Requires=db,auth,cache\n[Container]\n"
	got := parseRequires(content)
	want := []string{"db", "auth", "cache"}
	if len(got) != len(want) {
		t.Fatalf("expected %v, got %v", want, got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("index %d: got %q, want %q", i, got[i], want[i])
		}
	}
}

func TestParseRequires_EmptyValue(t *testing.T) {
	got := parseRequires("# Requires=\n[Container]\n")
	if len(got) != 0 {
		t.Errorf("expected nil for empty Requires=, got %v", got)
	}
}

// ---------------------------------------------------------------------------
// topoSortContainers
// ---------------------------------------------------------------------------

func TestTopoSort_NoDeps(t *testing.T) {
	// Three containers with no requires: graph — output must be alphabetical.
	containers := map[string]string{
		"ownbase-z": "ownbase-z.container",
		"ownbase-a": "ownbase-a.container",
		"ownbase-m": "ownbase-m.container",
	}
	contents := map[string]string{
		"ownbase-z.container": "# Generated\n[Container]\n",
		"ownbase-a.container": "# Generated\n[Container]\n",
		"ownbase-m.container": "# Generated\n[Container]\n",
	}
	result, err := topoSortContainers(containers, contents)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result) != 3 {
		t.Fatalf("want 3, got %d", len(result))
	}
	// Without deps the order is stable alphabetical (Kahn's picks zero-in-degree
	// nodes in sorted order).
	want := []string{"ownbase-a", "ownbase-m", "ownbase-z"}
	for i := range want {
		if result[i] != want[i] {
			t.Errorf("position %d: got %q, want %q", i, result[i], want[i])
		}
	}
}

func TestTopoSort_ProviderBeforeConsumer(t *testing.T) {
	// hello requires auth — auth must appear first.
	containers := map[string]string{
		"ownbase-hello": "ownbase-hello.container",
		"ownbase-auth":  "ownbase-auth.container",
	}
	contents := map[string]string{
		"ownbase-hello.container": "# Requires=auth\n[Container]\n",
		"ownbase-auth.container":  "# Generated\n[Container]\n",
	}
	result, err := topoSortContainers(containers, contents)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result) != 2 {
		t.Fatalf("want 2 results, got %d", len(result))
	}
	if result[0] != "ownbase-auth" || result[1] != "ownbase-hello" {
		t.Errorf("expected [ownbase-auth, ownbase-hello], got %v", result)
	}
}

func TestTopoSort_ChainedDeps(t *testing.T) {
	// c → b → a: must be a, b, c
	containers := map[string]string{
		"ownbase-a": "ownbase-a.container",
		"ownbase-b": "ownbase-b.container",
		"ownbase-c": "ownbase-c.container",
	}
	contents := map[string]string{
		"ownbase-a.container": "# Generated\n",
		"ownbase-b.container": "# Requires=a\n",
		"ownbase-c.container": "# Requires=b\n",
	}
	result, err := topoSortContainers(containers, contents)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result[0] != "ownbase-a" || result[1] != "ownbase-b" || result[2] != "ownbase-c" {
		t.Errorf("expected a,b,c chain order, got %v", result)
	}
}

func TestTopoSort_CycleDetected(t *testing.T) {
	// a → b → a (cycle)
	containers := map[string]string{
		"ownbase-a": "ownbase-a.container",
		"ownbase-b": "ownbase-b.container",
	}
	contents := map[string]string{
		"ownbase-a.container": "# Requires=b\n",
		"ownbase-b.container": "# Requires=a\n",
	}
	_, err := topoSortContainers(containers, contents)
	if err == nil {
		t.Fatal("expected cycle error, got nil")
	}
	if !strings.Contains(err.Error(), "cycle") {
		t.Errorf("expected 'cycle' in error, got: %v", err)
	}
}
