//go:build integration

package podman

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ownbase/ownbase/internal/secrets"
)

const secretsTestUnit = `# Generated by OwnBase — do not hand-edit.

[Unit]
Description=OwnBase container: ownbase-api

[Container]
Image=localhost/ownbase-api:local
ContainerName=ownbase-api
Environment=REVOLVE_DEFAULT_REGION=mx

[Service]
Restart=always
`

func TestInsertSecretDirectives_AddsDirectivesInContainerSection(t *testing.T) {
	got := insertSecretDirectives(secretsTestUnit, "api",
		[]string{"POSTGRES_PASSWORD", "REVOLVE_DATABASE_URL"})

	for _, want := range []string{
		"Secret=ownbase-api-POSTGRES_PASSWORD,type=env,target=POSTGRES_PASSWORD\n",
		"Secret=ownbase-api-REVOLVE_DATABASE_URL,type=env,target=REVOLVE_DATABASE_URL\n",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("Secret directive %q missing:\n%s", want, got)
		}
	}
	// The directives must sit inside [Container], before the compiler-emitted
	// Environment= line.
	secretIdx := strings.Index(got, "Secret=")
	containerIdx := strings.Index(got, "[Container]")
	envIdx := strings.Index(got, "Environment=REVOLVE_DEFAULT_REGION")
	serviceIdx := strings.Index(got, "[Service]")
	if !(containerIdx < secretIdx && secretIdx < envIdx && envIdx < serviceIdx) {
		t.Fatalf("Secret directives misplaced (container=%d secret=%d env=%d service=%d):\n%s",
			containerIdx, secretIdx, envIdx, serviceIdx, got)
	}
}

func TestInsertSecretDirectives_NoContainerSectionUnchanged(t *testing.T) {
	const netUnit = "[Network]\nDriver=bridge\n"
	if got := insertSecretDirectives(netUnit, "api", []string{"X"}); got != netUnit {
		t.Fatalf("expected unchanged content, got:\n%s", got)
	}
}

func TestInjectSecrets_NoSecretsFileUnchanged(t *testing.T) {
	dir := t.TempDir()
	p := &Applier{SecretsDir: dir}
	got, err := p.injectSecrets("ownbase-api", "ownbase-api.container", secretsTestUnit)
	if err != nil {
		t.Fatalf("injectSecrets: %v", err)
	}
	if got != secretsTestUnit {
		t.Fatalf("expected unchanged content when no secrets file exists")
	}
}

func TestInjectSecrets_DecryptsAndInjects(t *testing.T) {
	dir := t.TempDir()

	// Generate an age key and encrypt a secrets file for service "api".
	keyPath := filepath.Join(dir, "key.age")
	id, err := secrets.GenerateAndSave(keyPath)
	if err != nil {
		t.Fatalf("generate age key: %v", err)
	}
	ciphertext, err := secrets.EncryptSecrets(id.Recipient(), map[string]string{
		"POSTGRES_PASSWORD":    "s3cr3t",
		"REVOLVE_DATABASE_URL": "postgresql+psycopg://revolve:s3cr3t@ownbase-postgres:5432/revolve",
	})
	if err != nil {
		t.Fatalf("encrypt secrets: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "api.yaml.age"), ciphertext, 0o600); err != nil {
		t.Fatalf("write secrets file: %v", err)
	}

	if _, err := exec.LookPath("podman"); err != nil {
		t.Skip("podman not available; skipping secret-injection integration test")
	}
	secretNames := []string{"ownbase-api-POSTGRES_PASSWORD", "ownbase-api-REVOLVE_DATABASE_URL"}
	rmSecrets := func() {
		for _, n := range secretNames {
			_ = exec.Command("podman", "secret", "rm", n).Run()
		}
	}
	rmSecrets()          // clean slate
	t.Cleanup(rmSecrets) // and clean up whatever the test registered

	p := &Applier{SecretsDir: dir, AgeKeyPath: keyPath}
	got, err := p.injectSecrets("ownbase-api", "ownbase-api.container", secretsTestUnit)
	if err != nil {
		t.Fatalf("injectSecrets: %v", err)
	}

	// The unit must reference each secret as an env-typed Podman secret, and
	// carry NO plaintext values or on-disk env file path.
	for _, want := range []string{
		"Secret=ownbase-api-POSTGRES_PASSWORD,type=env,target=POSTGRES_PASSWORD\n",
		"Secret=ownbase-api-REVOLVE_DATABASE_URL,type=env,target=REVOLVE_DATABASE_URL\n",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("unit missing Secret directive %q:\n%s", want, got)
		}
	}
	if strings.Contains(got, "EnvironmentFile=") {
		t.Fatalf("unit must not carry an EnvironmentFile directive:\n%s", got)
	}
	if strings.Contains(got, "s3cr3t") {
		t.Fatalf("unit leaks a plaintext secret value:\n%s", got)
	}

	// Plaintext must never land on disk: the old runtime env file must not exist.
	if _, err := os.Stat(filepath.Join(dir, "runtime", "api.env")); !os.IsNotExist(err) {
		t.Fatalf("plaintext env file must not be written to disk (stat err=%v)", err)
	}

	// Each value must be resolvable from the Podman secret store, proving the
	// plaintext was actually registered (streamed over stdin, not via disk).
	for _, name := range []string{"ownbase-api-POSTGRES_PASSWORD", "ownbase-api-REVOLVE_DATABASE_URL"} {
		if out, err := exec.Command("podman", "secret", "inspect", name).CombinedOutput(); err != nil {
			t.Fatalf("podman secret inspect %s failed: %v — %s", name, err, out)
		}
	}
}

const jobSecretsTestUnit = `# Generated by OwnBase — do not hand-edit.

[Unit]
Description=OwnBase container: ownbase-job-nightly-ingest

[Container]
Image=localhost/ownbase-api:local
ContainerName=ownbase-job-nightly-ingest
Exec=python scripts/nightly_ingest.py
# JobService=api

[Service]
Type=oneshot
Restart=no
`

// TestInjectSecrets_JobMergesServiceAndOwnSecrets verifies that a job
// container inherits the referenced service's secrets (via the
// "# JobService=" provenance comment) and that the job's own secrets file
// (same <name>.yaml.age convention as a service) overrides a shared key
// without dropping the rest of the service's secrets.
func TestInjectSecrets_JobMergesServiceAndOwnSecrets(t *testing.T) {
	dir := t.TempDir()

	keyPath := filepath.Join(dir, "key.age")
	id, err := secrets.GenerateAndSave(keyPath)
	if err != nil {
		t.Fatalf("generate age key: %v", err)
	}

	// api's own secrets: two keys.
	apiCiphertext, err := secrets.EncryptSecrets(id.Recipient(), map[string]string{
		"REVOLVE_DATABASE_URL": "postgresql+psycopg://revolve:s3cr3t@ownbase-postgres:5432/revolve",
		"SHARED_KEY":           "from-service",
	})
	if err != nil {
		t.Fatalf("encrypt api secrets: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "api.yaml.age"), apiCiphertext, 0o600); err != nil {
		t.Fatalf("write api secrets file: %v", err)
	}

	// The job's own secrets: overrides SHARED_KEY, adds a job-only key.
	jobCiphertext, err := secrets.EncryptSecrets(id.Recipient(), map[string]string{
		"SHARED_KEY":     "from-job",
		"FEED_URL_TOKEN": "job-only-token",
	})
	if err != nil {
		t.Fatalf("encrypt job secrets: %v", err)
	}
	// Job secrets are keyed by the bare job name ("nightly-ingest"), the
	// same way `ownbasectl secrets set <base> nightly-ingest ...` would
	// write them — never "job-nightly-ingest".
	if err := os.WriteFile(filepath.Join(dir, "nightly-ingest.yaml.age"), jobCiphertext, 0o600); err != nil {
		t.Fatalf("write job secrets file: %v", err)
	}

	if _, err := exec.LookPath("podman"); err != nil {
		t.Skip("podman not available; skipping secret-injection integration test")
	}
	secretNames := []string{
		"ownbase-job-nightly-ingest-REVOLVE_DATABASE_URL",
		"ownbase-job-nightly-ingest-SHARED_KEY",
		"ownbase-job-nightly-ingest-FEED_URL_TOKEN",
	}
	rmSecrets := func() {
		for _, n := range secretNames {
			_ = exec.Command("podman", "secret", "rm", n).Run()
		}
	}
	rmSecrets()
	t.Cleanup(rmSecrets)

	p := &Applier{SecretsDir: dir, AgeKeyPath: keyPath}
	got, err := p.injectSecrets("ownbase-job-nightly-ingest", "ownbase-job-nightly-ingest.container", jobSecretsTestUnit)
	if err != nil {
		t.Fatalf("injectSecrets: %v", err)
	}

	// All three keys (two from the service, one job-only) must be injected,
	// namespaced under the job's own name — never the service's.
	for _, want := range []string{
		"Secret=ownbase-job-nightly-ingest-REVOLVE_DATABASE_URL,type=env,target=REVOLVE_DATABASE_URL\n",
		"Secret=ownbase-job-nightly-ingest-SHARED_KEY,type=env,target=SHARED_KEY\n",
		"Secret=ownbase-job-nightly-ingest-FEED_URL_TOKEN,type=env,target=FEED_URL_TOKEN\n",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("unit missing Secret directive %q:\n%s", want, got)
		}
	}

	// The job's own value must win the SHARED_KEY collision.
	out, err := exec.Command("podman", "secret", "exists", "ownbase-job-nightly-ingest-SHARED_KEY").CombinedOutput()
	if err != nil {
		t.Fatalf("podman secret exists ownbase-job-nightly-ingest-SHARED_KEY failed: %v — %s", err, out)
	}
}

// TestInjectSecrets_JobFallsBackToOwnSecretsOnly_WhenServiceHasNone verifies
// that a job with no referenced-service secrets file still injects its own.
func TestInjectSecrets_JobFallsBackToOwnSecretsOnly_WhenServiceHasNone(t *testing.T) {
	dir := t.TempDir()

	keyPath := filepath.Join(dir, "key.age")
	id, err := secrets.GenerateAndSave(keyPath)
	if err != nil {
		t.Fatalf("generate age key: %v", err)
	}
	jobCiphertext, err := secrets.EncryptSecrets(id.Recipient(), map[string]string{
		"FEED_URL_TOKEN": "job-only-token",
	})
	if err != nil {
		t.Fatalf("encrypt job secrets: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "nightly-ingest.yaml.age"), jobCiphertext, 0o600); err != nil {
		t.Fatalf("write job secrets file: %v", err)
	}
	// Deliberately no api.yaml.age file.

	if _, err := exec.LookPath("podman"); err != nil {
		t.Skip("podman not available; skipping secret-injection integration test")
	}
	const secretName = "ownbase-job-nightly-ingest-FEED_URL_TOKEN"
	_ = exec.Command("podman", "secret", "rm", secretName).Run()
	t.Cleanup(func() { _ = exec.Command("podman", "secret", "rm", secretName).Run() })

	p := &Applier{SecretsDir: dir, AgeKeyPath: keyPath}
	got, err := p.injectSecrets("ownbase-job-nightly-ingest", "ownbase-job-nightly-ingest.container", jobSecretsTestUnit)
	if err != nil {
		t.Fatalf("injectSecrets: %v", err)
	}
	want := "Secret=ownbase-job-nightly-ingest-FEED_URL_TOKEN,type=env,target=FEED_URL_TOKEN\n"
	if !strings.Contains(got, want) {
		t.Fatalf("unit missing Secret directive %q:\n%s", want, got)
	}
}

// ---------------------------------------------------------------------------
// unitToService — Quadlet's generated systemd service name per unit type
// ---------------------------------------------------------------------------

func TestUnitToService(t *testing.T) {
	cases := map[string]string{
		"ownbase-api.container":                "ownbase-api.service",
		"ownbase-job-nightly-ingest.container": "ownbase-job-nightly-ingest.service",
		"ownbase-api-net.network":              "ownbase-api-net-network.service",
		"ownbase-api-data.volume":              "ownbase-api-data-volume.service",
	}
	for unit, want := range cases {
		if got := unitToService(unit); got != want {
			t.Errorf("unitToService(%q) = %q, want %q", unit, got, want)
		}
	}
}
