//go:build integration

package podman_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/ownbase/ownbase/internal/authz"
	"github.com/ownbase/ownbase/internal/compiler"
	"github.com/ownbase/ownbase/internal/podman"
	"github.com/ownbase/ownbase/internal/reconcile"
	"github.com/ownbase/ownbase/internal/runtime"
	"github.com/ownbase/ownbase/internal/schema"
)

// testImage is pre-pulled by cloud-init; no registry pull needed during tests.
const testImage = "docker.io/library/alpine:latest"

// testContainerName must carry the OwnBase prefix so QueryCurrentState sees it.
const testContainerName = "ownbase-integtest"
const testUnitFilename = testContainerName + ".container"

func testQuadletUnit() string {
	return `# Generated by OwnBase integration tests — do not hand-edit.
[Unit]
Description=OwnBase integration-test container ` + testContainerName + `

[Container]
Image=` + testImage + `
ContainerName=` + testContainerName + `
Exec=sleep infinity

[Service]
Restart=no

[Install]
WantedBy=default.target
`
}

// testApplier returns a podman.Applier pointed at the standard user Quadlet dir.
func testApplier(t *testing.T) *podman.Applier {
	t.Helper()
	home, err := os.UserHomeDir()
	if err != nil {
		t.Fatalf("UserHomeDir: %v", err)
	}
	dir := filepath.Join(home, ".config/containers/systemd")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir quadlet dir: %v", err)
	}
	return &podman.Applier{QuadletDir: dir}
}

func testStartAction() reconcile.PlannedAction {
	return reconcile.PlannedAction{
		Action:       schema.MustNewAction(schema.ActionServiceStart, testContainerName),
		Description:  "start integration-test container",
		Before:       "not running",
		After:        "running",
		UnitFilename: testUnitFilename,
		UnitContent:  testQuadletUnit(),
	}
}

func testStopAction() reconcile.PlannedAction {
	return reconcile.PlannedAction{
		Action:       schema.MustNewAction(schema.ActionServiceStop, testContainerName),
		Description:  "stop integration-test container",
		Before:       "running",
		After:        "not running",
		UnitFilename: testUnitFilename,
	}
}

// ensureClean stops+removes the test container before and after each test.
// It also resets the systemd failed state and removes the podman container
// from storage, which can linger after an interrupted test run (e.g. when
// the test process is killed and ExecStopPost never ran).
func ensureClean(t *testing.T, a *podman.Applier) {
	t.Helper()
	clean := func() {
		_ = a.RollbackAction(testStartAction())
		// Quadlet ExecStop uses SIGTERM (10 s) then SIGKILL (exit 137), which
		// leaves the service in "failed" state. Clear it so the next start is
		// not blocked and so the warning "unit file changed" is suppressed.
		exec.Command("systemctl", "--user", "reset-failed",
			testContainerName+".service").Run()
		// Belt-and-suspenders: remove the container from podman storage in case
		// ExecStopPost did not run (e.g. after an interrupted test run).
		exec.Command("podman", "rm", "-f", testContainerName).Run()
	}
	clean()
	t.Cleanup(clean)
}

// testDesiredOutput builds the minimal compiler.RuntimeOutput for the test
// container (no network, no volume) so Diff can produce the correct plan.
func testDesiredOutput() compiler.RuntimeOutput {
	return compiler.RuntimeOutput{
		QuadletUnits: map[string]string{
			testUnitFilename: testQuadletUnit(),
		},
	}
}

// waitNotRunning polls until the container is no longer running or timeout.
func waitNotRunning(t *testing.T, name string, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		state, err := runtime.QueryCurrentState()
		if err != nil {
			t.Fatalf("QueryCurrentState: %v", err)
		}
		if !state.RunningContainers[name] {
			return
		}
		time.Sleep(500 * time.Millisecond)
	}
	t.Errorf("container %q still running after %s", name, timeout)
}

// ---------------------------------------------------------------------------
// QueryCurrentState
// ---------------------------------------------------------------------------

func TestQueryCurrentState_ReturnsState(t *testing.T) {
	state, err := runtime.QueryCurrentState()
	if err != nil {
		t.Fatalf("QueryCurrentState: %v", err)
	}
	_ = state // just verify it doesn't error; content is dynamic
}

// ---------------------------------------------------------------------------
// Start / Stop
// ---------------------------------------------------------------------------

func TestApplier_StartAndStop(t *testing.T) {
	a := testApplier(t)
	ensureClean(t, a)

	if err := a.ApplyAction(testStartAction()); err != nil {
		t.Fatalf("ApplyAction(start): %v", err)
	}

	state, err := runtime.QueryCurrentState()
	if err != nil {
		t.Fatalf("QueryCurrentState after start: %v", err)
	}
	if !state.RunningContainers[testContainerName] {
		t.Errorf("expected %q running, got containers: %v", testContainerName, state.RunningContainers)
	}

	if err := a.ApplyAction(testStopAction()); err != nil {
		t.Fatalf("ApplyAction(stop): %v", err)
	}
	waitNotRunning(t, testContainerName, 15*time.Second)
}

// ---------------------------------------------------------------------------
// Rollback
// ---------------------------------------------------------------------------

func TestApplier_RollbackStopsStartedContainer(t *testing.T) {
	a := testApplier(t)
	ensureClean(t, a)

	if err := a.ApplyAction(testStartAction()); err != nil {
		t.Fatalf("start: %v", err)
	}
	if err := a.RollbackAction(testStartAction()); err != nil {
		t.Fatalf("RollbackAction: %v", err)
	}
	waitNotRunning(t, testContainerName, 15*time.Second)
}

// ---------------------------------------------------------------------------
// Full reconcile loop — convergence
// ---------------------------------------------------------------------------

func TestReconcileConvergence_StartFromEmpty(t *testing.T) {
	a := testApplier(t)
	ensureClean(t, a)

	plan := reconcile.Plan{Actions: []reconcile.PlannedAction{testStartAction()}}
	mem := &authz.MemAuditLog{}

	if err := reconcile.Apply(plan, authz.NewTrivialCheckpoint(), a, mem); err != nil {
		t.Fatalf("Apply: %v", err)
	}

	for i, r := range mem.Records {
		if r.Outcome != authz.OutcomeApplied {
			t.Errorf("audit record %d: outcome %q, want %q", i, r.Outcome, authz.OutcomeApplied)
		}
	}

	state, err := runtime.QueryCurrentState()
	if err != nil {
		t.Fatalf("QueryCurrentState: %v", err)
	}
	if !state.RunningContainers[testContainerName] {
		t.Errorf("expected %q running after Apply, got: %v", testContainerName, state.RunningContainers)
	}
}

func TestReconcileIdempotency_SecondDiffIsEmpty(t *testing.T) {
	a := testApplier(t)
	ensureClean(t, a)

	plan1 := reconcile.Plan{Actions: []reconcile.PlannedAction{testStartAction()}}
	if err := reconcile.Apply(plan1, authz.NewTrivialCheckpoint(), a, authz.NopAuditLog()); err != nil {
		t.Fatalf("first Apply: %v", err)
	}

	current, err := runtime.QueryCurrentState()
	if err != nil {
		t.Fatalf("QueryCurrentState: %v", err)
	}
	if !current.RunningContainers[testContainerName] {
		t.Fatalf("container not running after first Apply")
	}

	// Scope the re-diff to this test's container only. Other integration test
	// packages (e.g. internal/update) run in parallel and may have their own
	// ownbase-* containers running, which would cause a spurious "stop" action.
	scoped := runtime.FakeCurrentState([]string{testContainerName})
	plan2, err := reconcile.Diff(testDesiredOutput(), scoped, reconcile.DiffOptions{})
	if err != nil {
		t.Fatalf("Diff: %v", err)
	}
	if !plan2.IsEmpty() {
		t.Errorf("expected empty plan on re-diff, got %d action(s):\n%s",
			len(plan2.Actions), reconcile.RenderPlanText(plan2))
	}
}

// ---------------------------------------------------------------------------
// Transactional rollback on mid-plan failure
// ---------------------------------------------------------------------------

func TestReconcile_RollbackOnFailure(t *testing.T) {
	a := testApplier(t)
	ensureClean(t, a)

	// Second action has no unit content — will fail immediately.
	badAction := reconcile.PlannedAction{
		Action:       schema.MustNewAction(schema.ActionServiceStart, "ownbase-bad"),
		UnitFilename: "ownbase-bad.container",
		UnitContent:  "", // triggers "no unit content" error
	}

	plan := reconcile.Plan{Actions: []reconcile.PlannedAction{testStartAction(), badAction}}
	mem := &authz.MemAuditLog{}

	err := reconcile.Apply(plan, authz.NewTrivialCheckpoint(), a, mem)
	if err == nil {
		t.Fatal("expected Apply to fail on the second action")
	}

	// First container must be rolled back.
	waitNotRunning(t, testContainerName, 15*time.Second)

	var hasError, hasRollback bool
	for _, r := range mem.Records {
		if r.Outcome == authz.OutcomeError {
			hasError = true
		}
		if r.Outcome == authz.OutcomeRolledBack {
			hasRollback = true
		}
	}
	if !hasError {
		t.Error("expected 'error' record in audit log")
	}
	if !hasRollback {
		t.Error("expected 'rolled_back' record in audit log")
	}
}
