package podman

import (
	"strings"
	"testing"
)

const stripTestUnit = `# Generated by OwnBase — do not hand-edit.

[Unit]
Description=OwnBase container: ownbase-api

[Container]
Image=localhost/ownbase-api:local
ContainerName=ownbase-api
Environment=REVOLVE_DEFAULT_REGION=mx

[Service]
Restart=always
`

// A unit that carries an apply-time secrets block must strip back to exactly the
// compiler's output, so the reconcile diff sees no drift and does not restart.
// The injected block is built directly (mirroring insertEnvironmentFile, which
// is integration-tagged) so this test runs in the default build too.
func TestStripInjectedSecrets_RoundTripsToCompilerOutput(t *testing.T) {
	block := injectedSecretsMarker + "\nEnvironmentFile=/opt/ownbase/secrets/runtime/api.env\n"
	injected := strings.Replace(stripTestUnit, "[Container]\n", "[Container]\n"+block, 1)
	if !strings.Contains(injected, "EnvironmentFile=") {
		t.Fatalf("precondition: injected unit missing EnvironmentFile:\n%s", injected)
	}
	if got := StripInjectedSecrets(injected); got != stripTestUnit {
		t.Fatalf("strip did not round-trip to compiler output:\n--- got ---\n%s\n--- want ---\n%s", got, stripTestUnit)
	}
}

// Units without an injected block (the common case: no secrets) must pass
// through byte-for-byte.
func TestStripInjectedSecrets_NoBlockUnchanged(t *testing.T) {
	if got := StripInjectedSecrets(stripTestUnit); got != stripTestUnit {
		t.Fatalf("expected unchanged content, got:\n%s", got)
	}
}
