package podman

import (
	"strings"
	"testing"
)

const stripTestUnit = `# Generated by OwnBase — do not hand-edit.

[Unit]
Description=OwnBase container: ownbase-api

[Container]
Image=localhost/ownbase-api:local
ContainerName=ownbase-api
Environment=REVOLVE_DEFAULT_REGION=mx

[Service]
Restart=always
`

// A unit that carries an apply-time secrets block must strip back to exactly the
// compiler's output, so the reconcile diff sees no drift and does not restart.
// The injected block is built directly (mirroring insertSecretDirectives, which
// is integration-tagged) so this test runs in the default build too.
func TestStripInjectedSecrets_RoundTripsToCompilerOutput(t *testing.T) {
	block := injectedSecretsMarker + "\n" +
		"Secret=ownbase-api-POSTGRES_PASSWORD,type=env,target=POSTGRES_PASSWORD\n" +
		"Secret=ownbase-api-REVOLVE_DATABASE_URL,type=env,target=REVOLVE_DATABASE_URL\n"
	injected := strings.Replace(stripTestUnit, "[Container]\n", "[Container]\n"+block, 1)
	if !strings.Contains(injected, "Secret=") {
		t.Fatalf("precondition: injected unit missing Secret= directives:\n%s", injected)
	}
	if got := StripInjectedSecrets(injected); got != stripTestUnit {
		t.Fatalf("strip did not round-trip to compiler output:\n--- got ---\n%s\n--- want ---\n%s", got, stripTestUnit)
	}
}

// Units without an injected block (the common case: no secrets) must pass
// through byte-for-byte.
func TestStripInjectedSecrets_NoBlockUnchanged(t *testing.T) {
	if got := StripInjectedSecrets(stripTestUnit); got != stripTestUnit {
		t.Fatalf("expected unchanged content, got:\n%s", got)
	}
}

// The daemon appends a secrets-fingerprint comment to the desired unit so a
// secrets change triggers a restart. Stripping the injected Secret= block must
// leave that fingerprint intact, otherwise the current-vs-desired comparison
// would never see the last-applied fingerprint and would restart every tick.
func TestStripInjectedSecrets_PreservesFingerprint(t *testing.T) {
	const fingerprint = "# ownbase:secrets-fingerprint=deadbeef\n"
	desiredWithFingerprint := stripTestUnit + fingerprint

	block := injectedSecretsMarker + "\n" +
		"Secret=ownbase-api-POSTGRES_PASSWORD,type=env,target=POSTGRES_PASSWORD\n"
	injected := strings.Replace(desiredWithFingerprint, "[Container]\n", "[Container]\n"+block, 1)

	got := StripInjectedSecrets(injected)
	if strings.Contains(got, "Secret=") {
		t.Fatalf("Secret= directive not stripped:\n%s", got)
	}
	if !strings.Contains(got, fingerprint) {
		t.Fatalf("secrets fingerprint must be preserved:\n%s", got)
	}
	if got != desiredWithFingerprint {
		t.Fatalf("strip did not round-trip to desired-with-fingerprint:\n--- got ---\n%s\n--- want ---\n%s", got, desiredWithFingerprint)
	}
}
