// Tier-1 tests for provenance comment parsing. No build-tag constraint —
// these run on macOS, CI, and Ubuntu alike.
package podman

import (
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// parseBuildProvenance
// ---------------------------------------------------------------------------

func TestParseBuildProvenance_AllFields(t *testing.T) {
	unit := "# BuildSource=services/auth\n# BuildRef=v1.0.0\n# BuildDockerfile=Dockerfile.prod\n# BuildContext=backend\n[Container]\n"
	src, ref, df, ctx := parseBuildProvenance(unit)
	if src != "services/auth" {
		t.Errorf("source: got %q, want %q", src, "services/auth")
	}
	if ref != "v1.0.0" {
		t.Errorf("ref: got %q, want %q", ref, "v1.0.0")
	}
	if df != "Dockerfile.prod" {
		t.Errorf("dockerfile: got %q, want %q", df, "Dockerfile.prod")
	}
	if ctx != "backend" {
		t.Errorf("context: got %q, want %q", ctx, "backend")
	}
}

func TestParseBuildProvenance_ImageBundled(t *testing.T) {
	// Image-bundled units have no BuildSource comment.
	unit := "# Generated by OwnBase\n[Container]\nImage=docker.io/caddy:latest\n"
	src, ref, df, ctx := parseBuildProvenance(unit)
	if src != "" || ref != "" || df != "" || ctx != "" {
		t.Errorf("expected all empty for image-bundled unit, got src=%q ref=%q df=%q ctx=%q",
			src, ref, df, ctx)
	}
}

// ---------------------------------------------------------------------------
// parseStartProvenance (M11 Tier-1 seam)
// ---------------------------------------------------------------------------

func TestParseStartProvenance_HealthProbe(t *testing.T) {
	unit := "# HealthProbeHTTP=/health\n[Container]\n"
	hp := parseStartProvenance(unit)
	if hp != "/health" {
		t.Errorf("healthProbeURL: got %q, want %q", hp, "/health")
	}
}

func TestParseStartProvenance_NoSecretsFileInUnit(t *testing.T) {
	// Units must never contain # SecretsFile= — secrets are discovered by
	// convention, not from unit content.
	unit := "# HealthProbeHTTP=/health\n[Container]\nEnvironment=FOO=bar\n"
	if strings.Contains(unit, "SecretsFile") {
		t.Errorf("unit must not contain SecretsFile annotation")
	}
	hp := parseStartProvenance(unit)
	if hp != "/health" {
		t.Errorf("healthProbeURL: got %q, want %q", hp, "/health")
	}
}

func TestParseStartProvenance_NoDirectives(t *testing.T) {
	unit := "# BuildSource=services/auth\n[Container]\n"
	hp := parseStartProvenance(unit)
	if hp != "" {
		t.Errorf("expected empty healthProbeURL, got %q", hp)
	}
}

// ---------------------------------------------------------------------------
// buildCloneURL — M14: token must NOT appear in the URL (M14)
// ---------------------------------------------------------------------------

func TestBuildCloneURL_NoTokenInURL(t *testing.T) {
	tests := []struct {
		baseURL string
		owner   string
		repo    string
		want    string
	}{
		{
			baseURL: "http://localhost:3000",
			owner:   "ownbase",
			repo:    "auth",
			want:    "http://localhost:3000/ownbase/auth.git",
		},
		{
			baseURL: "https://git.example.com",
			owner:   "myorg",
			repo:    "services",
			want:    "https://git.example.com/myorg/services.git",
		},
		{
			baseURL: "http://localhost:3000/",
			owner:   "ownbase",
			repo:    "crm",
			want:    "http://localhost:3000/ownbase/crm.git",
		},
	}
	for _, tc := range tests {
		got := buildCloneURL(tc.baseURL, tc.owner, tc.repo)
		if got != tc.want {
			t.Errorf("buildCloneURL(%q, %q, %q) = %q, want %q",
				tc.baseURL, tc.owner, tc.repo, got, tc.want)
		}
		// Critical: no `:token@` style embedding should be present.
		if contains(got, "@") {
			t.Errorf("buildCloneURL output contains '@' (possible credential embedding): %q", got)
		}
	}
}

// TestBuildCloneURL_NeverEmbedToken verifies that passing any combination of
// inputs never produces a URL with an embedded credential.
func TestBuildCloneURL_NeverEmbedToken(t *testing.T) {
	// Even if called with a base URL that looks like it has credentials, the
	// function should produce a clean URL for owner/repo.
	got := buildCloneURL("http://localhost:3000", "ownbase", "my-service")
	if contains(got, "token") || contains(got, "secret") || contains(got, "@") {
		t.Errorf("buildCloneURL produced URL with embedded credential: %q", got)
	}
}

// ---------------------------------------------------------------------------
// scrubToken — M14: credentials must be removed from error strings
// ---------------------------------------------------------------------------

func TestScrubToken_RemovesToken(t *testing.T) {
	token := "ghs_supersecrettoken"
	input := "fatal: could not access 'http://x-token:ghs_supersecrettoken@localhost:3000/ownbase/auth.git'"
	want := "fatal: could not access 'http://x-token:<redacted>@localhost:3000/ownbase/auth.git'"
	got := scrubToken(input, token)
	if got != want {
		t.Errorf("scrubToken:\n  got  %q\n  want %q", got, want)
	}
}

func TestScrubToken_EmptyToken_NoChange(t *testing.T) {
	input := "some error message"
	got := scrubToken(input, "")
	if got != input {
		t.Errorf("scrubToken with empty token changed input: %q → %q", input, got)
	}
}

func TestScrubToken_TokenNotInString_NoChange(t *testing.T) {
	input := "some harmless error"
	got := scrubToken(input, "supersecret")
	if got != input {
		t.Errorf("scrubToken changed string when token was absent: %q → %q", input, got)
	}
}

// ---------------------------------------------------------------------------
// quadletDirFor — root-aware Quadlet install directory (A: applier root parity)
// ---------------------------------------------------------------------------

func TestQuadletDirFor_Root(t *testing.T) {
	// Root must use the system path so units are managed by the system
	// systemctl manager (no user D-Bus session exists for root in a service).
	got := quadletDirFor(true, "/root")
	if got != SystemQuadletDir {
		t.Errorf("quadletDirFor(root) = %q, want %q", got, SystemQuadletDir)
	}
	// Home is irrelevant when root.
	if got := quadletDirFor(true, "/home/ownbase"); got != SystemQuadletDir {
		t.Errorf("quadletDirFor(root, home) = %q, want %q (home must be ignored)", got, SystemQuadletDir)
	}
}

func TestQuadletDirFor_NonRoot(t *testing.T) {
	got := quadletDirFor(false, "/home/ownbase")
	want := "/home/ownbase/" + QuadletUserDir
	if got != want {
		t.Errorf("quadletDirFor(non-root) = %q, want %q", got, want)
	}
}

func TestQuadletDirFor_NonRootEmptyHome(t *testing.T) {
	// An empty home must fall back to /root rather than producing a relative
	// path that would write units into the process working directory.
	got := quadletDirFor(false, "")
	want := "/root/" + QuadletUserDir
	if got != want {
		t.Errorf("quadletDirFor(non-root, empty home) = %q, want %q", got, want)
	}
}

// ---------------------------------------------------------------------------
// systemctlArgs — root uses the system manager; non-root uses --user
// ---------------------------------------------------------------------------

func TestSystemctlArgs_RootOmitsUserFlag(t *testing.T) {
	got := systemctlArgs(true, "start", "ownbase-auth.service")
	want := []string{"start", "ownbase-auth.service"}
	if !equalStrings(got, want) {
		t.Errorf("systemctlArgs(root) = %v, want %v (must not contain --user)", got, want)
	}
	for _, a := range got {
		if a == "--user" {
			t.Fatalf("systemctlArgs(root) leaked --user: %v", got)
		}
	}
}

func TestSystemctlArgs_NonRootPrependsUserFlag(t *testing.T) {
	got := systemctlArgs(false, "start", "ownbase-auth.service")
	want := []string{"--user", "start", "ownbase-auth.service"}
	if !equalStrings(got, want) {
		t.Errorf("systemctlArgs(non-root) = %v, want %v", got, want)
	}
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func contains(s, sub string) bool {
	return len(sub) > 0 && len(s) >= len(sub) && func() bool {
		for i := 0; i <= len(s)-len(sub); i++ {
			if s[i:i+len(sub)] == sub {
				return true
			}
		}
		return false
	}()
}

// ---------------------------------------------------------------------------
// parseQuadletComment
// ---------------------------------------------------------------------------

func TestParseQuadletComment_Present(t *testing.T) {
	unit := "[Container]\n# HealthProbeHTTP=/health\nImage=docker.io/foo:latest\n"
	got := parseQuadletComment("HealthProbeHTTP", unit)
	if got != "/health" {
		t.Errorf("parseQuadletComment(HealthProbeHTTP) = %q, want %q", got, "/health")
	}
}

func TestParseQuadletComment_Absent(t *testing.T) {
	unit := "[Container]\nImage=docker.io/foo:latest\n"
	got := parseQuadletComment("HealthProbeHTTP", unit)
	if got != "" {
		t.Errorf("parseQuadletComment(HealthProbeHTTP) absent: got %q, want empty", got)
	}
}

// ---------------------------------------------------------------------------
// parsePublishPort
// ---------------------------------------------------------------------------

func TestParsePublishPort_FullFormat(t *testing.T) {
	unit := "[Container]\nPublishPort=127.0.0.1:8080:8080\nImage=docker.io/foo:latest\n"
	got := parsePublishPort(unit)
	if got != 8080 {
		t.Errorf("parsePublishPort = %d, want 8080", got)
	}
}

func TestParsePublishPort_NoIPPrefix(t *testing.T) {
	unit := "[Container]\nPublishPort=3000:3000\nImage=docker.io/foo:latest\n"
	got := parsePublishPort(unit)
	if got != 3000 {
		t.Errorf("parsePublishPort(no IP) = %d, want 3000", got)
	}
}

func TestParsePublishPort_Absent(t *testing.T) {
	unit := "[Container]\nImage=docker.io/foo:latest\n"
	got := parsePublishPort(unit)
	if got != 0 {
		t.Errorf("parsePublishPort(absent) = %d, want 0", got)
	}
}
