//go:build integration

package podman

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ownbase/ownbase/internal/secrets"
)

const secretsTestUnit = `# Generated by OwnBase — do not hand-edit.

[Unit]
Description=OwnBase container: ownbase-api

[Container]
Image=localhost/ownbase-api:local
ContainerName=ownbase-api
Environment=REVOLVE_DEFAULT_REGION=mx

[Service]
Restart=always
`

func TestInsertEnvironmentFile_AddsDirectiveInContainerSection(t *testing.T) {
	got := insertEnvironmentFile(secretsTestUnit, "/opt/ownbase/secrets/runtime/api.env")

	if !strings.Contains(got, "EnvironmentFile=/opt/ownbase/secrets/runtime/api.env\n") {
		t.Fatalf("EnvironmentFile directive missing:\n%s", got)
	}
	// It must sit inside [Container], before the compiler-emitted Environment= line.
	envFileIdx := strings.Index(got, "EnvironmentFile=")
	containerIdx := strings.Index(got, "[Container]")
	envIdx := strings.Index(got, "Environment=REVOLVE_DEFAULT_REGION")
	serviceIdx := strings.Index(got, "[Service]")
	if !(containerIdx < envFileIdx && envFileIdx < envIdx && envIdx < serviceIdx) {
		t.Fatalf("EnvironmentFile directive misplaced (container=%d envfile=%d env=%d service=%d):\n%s",
			containerIdx, envFileIdx, envIdx, serviceIdx, got)
	}
}

func TestInsertEnvironmentFile_NoContainerSectionUnchanged(t *testing.T) {
	const netUnit = "[Network]\nDriver=bridge\n"
	if got := insertEnvironmentFile(netUnit, "/x.env"); got != netUnit {
		t.Fatalf("expected unchanged content, got:\n%s", got)
	}
}

func TestInjectSecrets_NoSecretsFileUnchanged(t *testing.T) {
	dir := t.TempDir()
	p := &Applier{SecretsDir: dir}
	got, err := p.injectSecrets("ownbase-api", "ownbase-api.container", secretsTestUnit)
	if err != nil {
		t.Fatalf("injectSecrets: %v", err)
	}
	if got != secretsTestUnit {
		t.Fatalf("expected unchanged content when no secrets file exists")
	}
}

func TestInjectSecrets_DecryptsAndInjects(t *testing.T) {
	dir := t.TempDir()

	// Generate an age key and encrypt a secrets file for service "api".
	keyPath := filepath.Join(dir, "key.age")
	id, err := secrets.GenerateAndSave(keyPath)
	if err != nil {
		t.Fatalf("generate age key: %v", err)
	}
	ciphertext, err := secrets.EncryptSecrets(id.Recipient(), map[string]string{
		"POSTGRES_PASSWORD":    "s3cr3t",
		"REVOLVE_DATABASE_URL": "postgresql+psycopg://revolve:s3cr3t@ownbase-postgres:5432/revolve",
	})
	if err != nil {
		t.Fatalf("encrypt secrets: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "api.yaml.age"), ciphertext, 0o600); err != nil {
		t.Fatalf("write secrets file: %v", err)
	}

	p := &Applier{SecretsDir: dir, AgeKeyPath: keyPath}
	got, err := p.injectSecrets("ownbase-api", "ownbase-api.container", secretsTestUnit)
	if err != nil {
		t.Fatalf("injectSecrets: %v", err)
	}

	envPath := filepath.Join(dir, "runtime", "api.env")
	if !strings.Contains(got, "EnvironmentFile="+envPath+"\n") {
		t.Fatalf("unit missing EnvironmentFile directive:\n%s", got)
	}

	// The env file must be 0600 and contain both secrets, sorted.
	info, err := os.Stat(envPath)
	if err != nil {
		t.Fatalf("stat env file: %v", err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Fatalf("env file perms = %o, want 0600", info.Mode().Perm())
	}
	data, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("read env file: %v", err)
	}
	want := "POSTGRES_PASSWORD=s3cr3t\n" +
		"REVOLVE_DATABASE_URL=postgresql+psycopg://revolve:s3cr3t@ownbase-postgres:5432/revolve\n"
	if string(data) != want {
		t.Fatalf("env file content =\n%q\nwant\n%q", string(data), want)
	}
}
