//go:build integration

package podman

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ownbase/ownbase/internal/secrets"
)

const secretsTestUnit = `# Generated by OwnBase — do not hand-edit.

[Unit]
Description=OwnBase container: ownbase-api

[Container]
Image=localhost/ownbase-api:local
ContainerName=ownbase-api
Environment=REVOLVE_DEFAULT_REGION=mx

[Service]
Restart=always
`

func TestInsertSecretDirectives_AddsDirectivesInContainerSection(t *testing.T) {
	got := insertSecretDirectives(secretsTestUnit, "api",
		[]string{"POSTGRES_PASSWORD", "REVOLVE_DATABASE_URL"})

	for _, want := range []string{
		"Secret=ownbase-api-POSTGRES_PASSWORD,type=env,target=POSTGRES_PASSWORD\n",
		"Secret=ownbase-api-REVOLVE_DATABASE_URL,type=env,target=REVOLVE_DATABASE_URL\n",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("Secret directive %q missing:\n%s", want, got)
		}
	}
	// The directives must sit inside [Container], before the compiler-emitted
	// Environment= line.
	secretIdx := strings.Index(got, "Secret=")
	containerIdx := strings.Index(got, "[Container]")
	envIdx := strings.Index(got, "Environment=REVOLVE_DEFAULT_REGION")
	serviceIdx := strings.Index(got, "[Service]")
	if !(containerIdx < secretIdx && secretIdx < envIdx && envIdx < serviceIdx) {
		t.Fatalf("Secret directives misplaced (container=%d secret=%d env=%d service=%d):\n%s",
			containerIdx, secretIdx, envIdx, serviceIdx, got)
	}
}

func TestInsertSecretDirectives_NoContainerSectionUnchanged(t *testing.T) {
	const netUnit = "[Network]\nDriver=bridge\n"
	if got := insertSecretDirectives(netUnit, "api", []string{"X"}); got != netUnit {
		t.Fatalf("expected unchanged content, got:\n%s", got)
	}
}

func TestInjectSecrets_NoSecretsFileUnchanged(t *testing.T) {
	dir := t.TempDir()
	p := &Applier{SecretsDir: dir}
	got, err := p.injectSecrets("ownbase-api", "ownbase-api.container", secretsTestUnit)
	if err != nil {
		t.Fatalf("injectSecrets: %v", err)
	}
	if got != secretsTestUnit {
		t.Fatalf("expected unchanged content when no secrets file exists")
	}
}

func TestInjectSecrets_DecryptsAndInjects(t *testing.T) {
	dir := t.TempDir()

	// Generate an age key and encrypt a secrets file for service "api".
	keyPath := filepath.Join(dir, "key.age")
	id, err := secrets.GenerateAndSave(keyPath)
	if err != nil {
		t.Fatalf("generate age key: %v", err)
	}
	ciphertext, err := secrets.EncryptSecrets(id.Recipient(), map[string]string{
		"POSTGRES_PASSWORD":    "s3cr3t",
		"REVOLVE_DATABASE_URL": "postgresql+psycopg://revolve:s3cr3t@ownbase-postgres:5432/revolve",
	})
	if err != nil {
		t.Fatalf("encrypt secrets: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "api.yaml.age"), ciphertext, 0o600); err != nil {
		t.Fatalf("write secrets file: %v", err)
	}

	if _, err := exec.LookPath("podman"); err != nil {
		t.Skip("podman not available; skipping secret-injection integration test")
	}
	secretNames := []string{"ownbase-api-POSTGRES_PASSWORD", "ownbase-api-REVOLVE_DATABASE_URL"}
	rmSecrets := func() {
		for _, n := range secretNames {
			_ = exec.Command("podman", "secret", "rm", n).Run()
		}
	}
	rmSecrets()          // clean slate
	t.Cleanup(rmSecrets) // and clean up whatever the test registered

	p := &Applier{SecretsDir: dir, AgeKeyPath: keyPath}
	got, err := p.injectSecrets("ownbase-api", "ownbase-api.container", secretsTestUnit)
	if err != nil {
		t.Fatalf("injectSecrets: %v", err)
	}

	// The unit must reference each secret as an env-typed Podman secret, and
	// carry NO plaintext values or on-disk env file path.
	for _, want := range []string{
		"Secret=ownbase-api-POSTGRES_PASSWORD,type=env,target=POSTGRES_PASSWORD\n",
		"Secret=ownbase-api-REVOLVE_DATABASE_URL,type=env,target=REVOLVE_DATABASE_URL\n",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("unit missing Secret directive %q:\n%s", want, got)
		}
	}
	if strings.Contains(got, "EnvironmentFile=") {
		t.Fatalf("unit must not carry an EnvironmentFile directive:\n%s", got)
	}
	if strings.Contains(got, "s3cr3t") {
		t.Fatalf("unit leaks a plaintext secret value:\n%s", got)
	}

	// Plaintext must never land on disk: the old runtime env file must not exist.
	if _, err := os.Stat(filepath.Join(dir, "runtime", "api.env")); !os.IsNotExist(err) {
		t.Fatalf("plaintext env file must not be written to disk (stat err=%v)", err)
	}

	// Each value must be resolvable from the Podman secret store, proving the
	// plaintext was actually registered (streamed over stdin, not via disk).
	for _, name := range []string{"ownbase-api-POSTGRES_PASSWORD", "ownbase-api-REVOLVE_DATABASE_URL"} {
		if out, err := exec.Command("podman", "secret", "inspect", name).CombinedOutput(); err != nil {
			t.Fatalf("podman secret inspect %s failed: %v — %s", name, err, out)
		}
	}
}
