// Tier-1 tests for provenance comment parsing. No build-tag constraint —
// these run on macOS, CI, and Ubuntu alike.
package podman

import (
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// parseBuildProvenance
// ---------------------------------------------------------------------------

func TestParseBuildProvenance_AllFields(t *testing.T) {
	unit := "# BuildSource=services/auth\n# BuildRef=v1.0.0\n# BuildDockerfile=Dockerfile.prod\n# BuildContext=backend\n[Container]\n"
	src, ref, df, ctx := parseBuildProvenance(unit)
	if src != "services/auth" {
		t.Errorf("source: got %q, want %q", src, "services/auth")
	}
	if ref != "v1.0.0" {
		t.Errorf("ref: got %q, want %q", ref, "v1.0.0")
	}
	if df != "Dockerfile.prod" {
		t.Errorf("dockerfile: got %q, want %q", df, "Dockerfile.prod")
	}
	if ctx != "backend" {
		t.Errorf("context: got %q, want %q", ctx, "backend")
	}
}

func TestParseBuildProvenance_ImageBundled(t *testing.T) {
	// Image-bundled units have no BuildSource comment.
	unit := "# Generated by OwnBase\n[Container]\nImage=docker.io/caddy:latest\n"
	src, ref, df, ctx := parseBuildProvenance(unit)
	if src != "" || ref != "" || df != "" || ctx != "" {
		t.Errorf("expected all empty for image-bundled unit, got src=%q ref=%q df=%q ctx=%q",
			src, ref, df, ctx)
	}
}

// ---------------------------------------------------------------------------
// parseStartProvenance (M11 Tier-1 seam)
// ---------------------------------------------------------------------------

func TestParseStartProvenance_HealthProbe(t *testing.T) {
	unit := "# HealthProbeHTTP=/health\n[Container]\n"
	hp := parseStartProvenance(unit)
	if hp != "/health" {
		t.Errorf("healthProbeURL: got %q, want %q", hp, "/health")
	}
}

func TestParseStartProvenance_NoSecretsFileInUnit(t *testing.T) {
	// Units must never contain # SecretsFile= — secrets are discovered by
	// convention, not from unit content.
	unit := "# HealthProbeHTTP=/health\n[Container]\nEnvironment=FOO=bar\n"
	if strings.Contains(unit, "SecretsFile") {
		t.Errorf("unit must not contain SecretsFile annotation")
	}
	hp := parseStartProvenance(unit)
	if hp != "/health" {
		t.Errorf("healthProbeURL: got %q, want %q", hp, "/health")
	}
}

func TestParseStartProvenance_NoDirectives(t *testing.T) {
	unit := "# BuildSource=services/auth\n[Container]\n"
	hp := parseStartProvenance(unit)
	if hp != "" {
		t.Errorf("expected empty healthProbeURL, got %q", hp)
	}
}

// ---------------------------------------------------------------------------
// quadletDirFor — root-aware Quadlet install directory (A: applier root parity)
// ---------------------------------------------------------------------------

func TestQuadletDirFor_Root(t *testing.T) {
	// Root must use the system path so units are managed by the system
	// systemctl manager (no user D-Bus session exists for root in a service).
	got := quadletDirFor(true, "/root")
	if got != SystemQuadletDir {
		t.Errorf("quadletDirFor(root) = %q, want %q", got, SystemQuadletDir)
	}
	// Home is irrelevant when root.
	if got := quadletDirFor(true, "/home/ownbase"); got != SystemQuadletDir {
		t.Errorf("quadletDirFor(root, home) = %q, want %q (home must be ignored)", got, SystemQuadletDir)
	}
}

func TestQuadletDirFor_NonRoot(t *testing.T) {
	got := quadletDirFor(false, "/home/ownbase")
	want := "/home/ownbase/" + QuadletUserDir
	if got != want {
		t.Errorf("quadletDirFor(non-root) = %q, want %q", got, want)
	}
}

func TestQuadletDirFor_NonRootEmptyHome(t *testing.T) {
	// An empty home must fall back to /root rather than producing a relative
	// path that would write units into the process working directory.
	got := quadletDirFor(false, "")
	want := "/root/" + QuadletUserDir
	if got != want {
		t.Errorf("quadletDirFor(non-root, empty home) = %q, want %q", got, want)
	}
}

// ---------------------------------------------------------------------------
// systemctlArgs — root uses the system manager; non-root uses --user
// ---------------------------------------------------------------------------

func TestSystemctlArgs_RootOmitsUserFlag(t *testing.T) {
	got := systemctlArgs(true, "start", "ownbase-auth.service")
	want := []string{"start", "ownbase-auth.service"}
	if !equalStrings(got, want) {
		t.Errorf("systemctlArgs(root) = %v, want %v (must not contain --user)", got, want)
	}
	for _, a := range got {
		if a == "--user" {
			t.Fatalf("systemctlArgs(root) leaked --user: %v", got)
		}
	}
}

func TestSystemctlArgs_NonRootPrependsUserFlag(t *testing.T) {
	got := systemctlArgs(false, "start", "ownbase-auth.service")
	want := []string{"--user", "start", "ownbase-auth.service"}
	if !equalStrings(got, want) {
		t.Errorf("systemctlArgs(non-root) = %v, want %v", got, want)
	}
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// ---------------------------------------------------------------------------
// parseQuadletComment
// ---------------------------------------------------------------------------

func TestParseQuadletComment_Present(t *testing.T) {
	unit := "[Container]\n# HealthProbeHTTP=/health\nImage=docker.io/foo:latest\n"
	got := parseQuadletComment("HealthProbeHTTP", unit)
	if got != "/health" {
		t.Errorf("parseQuadletComment(HealthProbeHTTP) = %q, want %q", got, "/health")
	}
}

func TestParseQuadletComment_Absent(t *testing.T) {
	unit := "[Container]\nImage=docker.io/foo:latest\n"
	got := parseQuadletComment("HealthProbeHTTP", unit)
	if got != "" {
		t.Errorf("parseQuadletComment(HealthProbeHTTP) absent: got %q, want empty", got)
	}
}

// ---------------------------------------------------------------------------
// parsePublishPort
// ---------------------------------------------------------------------------

func TestParsePublishPort_FullFormat(t *testing.T) {
	unit := "[Container]\nPublishPort=127.0.0.1:8080:8080\nImage=docker.io/foo:latest\n"
	got := parsePublishPort(unit)
	if got != 8080 {
		t.Errorf("parsePublishPort = %d, want 8080", got)
	}
}

func TestParsePublishPort_NoIPPrefix(t *testing.T) {
	unit := "[Container]\nPublishPort=3000:3000\nImage=docker.io/foo:latest\n"
	got := parsePublishPort(unit)
	if got != 3000 {
		t.Errorf("parsePublishPort(no IP) = %d, want 3000", got)
	}
}

func TestParsePublishPort_Absent(t *testing.T) {
	unit := "[Container]\nImage=docker.io/foo:latest\n"
	got := parsePublishPort(unit)
	if got != 0 {
		t.Errorf("parsePublishPort(absent) = %d, want 0", got)
	}
}

// ---------------------------------------------------------------------------
// timerDirFor — root-aware native systemd timer install directory
// ---------------------------------------------------------------------------

func TestTimerDirFor_Root(t *testing.T) {
	got := timerDirFor(true, "/root")
	if got != SystemTimerDir {
		t.Errorf("timerDirFor(root) = %q, want %q", got, SystemTimerDir)
	}
	// Home is irrelevant when root.
	if got := timerDirFor(true, "/home/ownbase"); got != SystemTimerDir {
		t.Errorf("timerDirFor(root, home) = %q, want %q (home must be ignored)", got, SystemTimerDir)
	}
}

func TestTimerDirFor_NonRoot(t *testing.T) {
	got := timerDirFor(false, "/home/ownbase")
	want := "/home/ownbase/" + TimerUserDir
	if got != want {
		t.Errorf("timerDirFor(non-root) = %q, want %q", got, want)
	}
}

func TestTimerDirFor_NonRootEmptyHome(t *testing.T) {
	got := timerDirFor(false, "")
	want := "/root/" + TimerUserDir
	if got != want {
		t.Errorf("timerDirFor(non-root, empty home) = %q, want %q", got, want)
	}
}

func TestTimerDirFor_DistinctFromQuadletDir(t *testing.T) {
	// SystemTimerDir/TimerUserDir must never collide with
	// SystemQuadletDir/QuadletUserDir — a .timer is not a Quadlet type and
	// must not be written into the Quadlet directory.
	if timerDirFor(true, "/root") == quadletDirFor(true, "/root") {
		t.Error("timerDirFor(root) must differ from quadletDirFor(root)")
	}
	if timerDirFor(false, "/home/ownbase") == quadletDirFor(false, "/home/ownbase") {
		t.Error("timerDirFor(non-root) must differ from quadletDirFor(non-root)")
	}
}

// ---------------------------------------------------------------------------
// isOwnbaseTimerFile — scopes the shared systemd unit dir to ownbase's own files
// ---------------------------------------------------------------------------

func TestIsOwnbaseTimerFile(t *testing.T) {
	cases := map[string]bool{
		"ownbase-job-nightly-ingest.timer":   true,
		"ownbase-job-cleanup.timer":          true,
		"apt-daily.timer":                    false,
		"fstrim.timer":                       false,
		"ownbase-api.container":              false,
		"ownbase-job-nightly-ingest.service": false,
	}
	for name, want := range cases {
		if got := isOwnbaseTimerFile(name); got != want {
			t.Errorf("isOwnbaseTimerFile(%q) = %v, want %v", name, got, want)
		}
	}
}

// TestParsePublishPort_DifferingHostAndContainerPorts is a regression test
// for the normal case since the dev-bridge port decoupling: the host
// (loopback) port and the container port are no longer required to match.
// parsePublishPort must always return the host port — the second-to-last
// colon-separated segment — regardless of whether it equals the container
// port.
func TestParsePublishPort_DifferingHostAndContainerPorts(t *testing.T) {
	unit := "[Container]\nPublishPort=127.0.0.1:41000:8080\nImage=docker.io/foo:latest\n"
	got := parsePublishPort(unit)
	if got != 41000 {
		t.Errorf("parsePublishPort(differing host/container) = %d, want 41000", got)
	}
}
